SV1 = {
    "Scarlet & Violet - Base Set": {
        "pull_rates": {
            "P_DR": 1/8, "P_IR": 1/13, "P_UR": 1/15, "P_SIR": 1/30, "P_HR": 1/56
        },
        "card_database": {
            "Common": [
                ("Pineco", "SVI", "001", "Common", "Pokémon"), ("Shroomish", "SVI", "003", "Common", "Pokémon"),
                ("Cacnea", "SVI", "005", "Common", "Pokémon"), ("Tropius", "SVI", "007", "Common", "Pokémon"),
                ("Scatterbug", "SVI", "008", "Common", "Pokémon"), ("Spewpa", "SVI", "009", "Common", "Pokémon"),
                ("Skiddo", "SVI", "011", "Common", "Pokémon"), ("Gogoat", "SVI", "012", "Common", "Pokémon"),
                ("Sprigatito", "SVI", "013", "Common", "Pokémon"), ("Tarountula", "SVI", "016", "Common", "Pokémon"),
                ("Tarountula", "SVI", "017", "Common", "Pokémon"), ("Tarountula", "SVI", "018", "Common", "Pokémon"),
                ("Smoliv", "SVI", "020", "Common", "Pokémon"), ("Smoliv", "SVI", "021", "Common", "Pokémon"),
                ("Dolliv", "SVI", "022", "Common", "Pokémon"), ("Toedscool", "SVI", "024", "Common", "Pokémon"),
                ("Toedscool", "SVI", "025", "Common", "Pokémon"), ("Capsakid", "SVI", "027", "Common", "Pokémon"),
                ("Capsakid", "SVI", "028", "Common", "Pokémon"), ("Growlithe", "SVI", "030", "Common", "Pokémon"),
                ("Growlithe", "SVI", "031", "Common", "Pokémon"), ("Houndour", "SVI", "033", "Common", "Pokémon"),
                ("Houndoom", "SVI", "034", "Common", "Pokémon"), ("Fuecoco", "SVI", "036", "Common", "Pokémon"),
                ("Charcadet", "SVI", "039", "Common", "Pokémon"), ("Charcadet", "SVI", "040", "Common", "Pokémon"),
                ("Slowpoke", "SVI", "042", "Common", "Pokémon"), ("Magikarp", "SVI", "044", "Common", "Pokémon"),
                ("Buizel", "SVI", "046", "Common", "Pokémon"), ("Alomomola", "SVI", "048", "Common", "Pokémon"),
                ("Clauncher", "SVI", "049", "Common", "Pokémon"), ("Clawitzer", "SVI", "050", "Common", "Pokémon"),
                ("Bruxish", "SVI", "051", "Common", "Pokémon"), ("Quaxly", "SVI", "052", "Common", "Pokémon"),
                ("Wiglett", "SVI", "055", "Common", "Pokémon"), ("Wiglett", "SVI", "056", "Common", "Pokémon"),
                ("Cetoddle", "SVI", "058", "Common", "Pokémon"), ("Cetoddle", "SVI", "059", "Common", "Pokémon"),
                ("Magnemite", "SVI", "063", "Common", "Pokémon"), ("Magneton", "SVI", "064", "Common", "Pokémon"),
                ("Mareep", "SVI", "066", "Common", "Pokémon"), ("Rotom", "SVI", "069", "Common", "Pokémon"),
                ("Rotom", "SVI", "070", "Common", "Pokémon"), ("Toxel", "SVI", "071", "Common", "Pokémon"),
                ("Pawmi", "SVI", "073", "Common", "Pokémon"), ("Pawmi", "SVI", "074", "Common", "Pokémon"),
                ("Pawmo", "SVI", "075", "Common", "Pokémon"), ("Wattrel", "SVI", "077", "Common", "Pokémon"),
                ("Wattrel", "SVI", "078", "Common", "Pokémon"), ("Drowzee", "SVI", "082", "Common", "Pokémon"),
                ("Ralts", "SVI", "084", "Common", "Pokémon"), ("Kirlia", "SVI", "085", "Common", "Pokémon"),
                ("Shuppet", "SVI", "087", "Common", "Pokémon"), ("Drifloon", "SVI", "089", "Common", "Pokémon"),
                ("Flabébé", "SVI", "091", "Common", "Pokémon"), ("Floette", "SVI", "092", "Common", "Pokémon"),
                ("Dedenne", "SVI", "094", "Common", "Pokémon"), ("Dedenne", "SVI", "095", "Common", "Pokémon"),
                ("Fidough", "SVI", "097", "Common", "Pokémon"), ("Fidough", "SVI", "098", "Common", "Pokémon"),
                ("Flittle", "SVI", "100", "Common", "Pokémon"), ("Flittle", "SVI", "101", "Common", "Pokémon"),
                ("Flittle", "SVI", "102", "Common", "Pokémon"), ("Greavard", "SVI", "104", "Common", "Pokémon"),
                ("Greavard", "SVI", "105", "Common", "Pokémon"), ("Mankey", "SVI", "107", "Common", "Pokémon"),
                ("Primeape", "SVI", "108", "Common", "Pokémon"), ("Meditite", "SVI", "110", "Common", "Pokémon"),
                ("Riolu", "SVI", "112", "Common", "Pokémon"), ("Riolu", "SVI", "113", "Common", "Pokémon"),
                ("Sandile", "SVI", "115", "Common", "Pokémon"), ("Krokorok", "SVI", "116", "Common", "Pokémon"),
                ("Silicobra", "SVI", "119", "Common", "Pokémon"), ("Grimer", "SVI", "126", "Common", "Pokémon"),
                ("Seviper", "SVI", "128", "Common", "Pokémon"), ("Croagunk", "SVI", "130", "Common", "Pokémon"),
                ("Pawniard", "SVI", "132", "Common", "Pokémon"), ("Bisharp", "SVI", "133", "Common", "Pokémon"),
                ("Maschiff", "SVI", "135", "Common", "Pokémon"), ("Maschiff", "SVI", "136", "Common", "Pokémon"),
                ("Varoom", "SVI", "140", "Common", "Pokémon"), ("Varoom", "SVI", "141", "Common", "Pokémon"),
                ("Chansey", "SVI", "144", "Common", "Pokémon"), ("Zangoose", "SVI", "146", "Common", "Pokémon"),
                ("Starly", "SVI", "148", "Common", "Pokémon"), ("Staravia", "SVI", "149", "Common", "Pokémon"),
                ("Skwovet", "SVI", "151", "Common", "Pokémon"), ("Lechonk", "SVI", "154", "Common", "Pokémon"),
                ("Lechonk", "SVI", "155", "Common", "Pokémon"), ("Lechonk", "SVI", "156", "Common", "Pokémon"),
                ("Tandemaus", "SVI", "159", "Common", "Pokémon"), ("Tandemaus", "SVI", "160", "Common", "Pokémon"),
                ("Squawkabilly", "SVI", "162", "Common", "Pokémon"), ("Crushing Hammer", "SVI", "168", "Common", "Trainer"),
                ("Energy Retrieval", "SVI", "171", "Common", "Trainer"), ("Energy Search", "SVI", "172", "Common", "Trainer"),
                ("Energy Switch", "SVI", "173", "Common", "Trainer"), ("Nemona", "SVI", "180", "Common", "Trainer"),
                ("Pal Pad", "SVI", "182", "Common", "Trainer"), ("Poké Ball", "SVI", "185", "Common", "Trainer"),
                ("Pokégear 3.0", "SVI", "186", "Common", "Trainer"), ("Pokémon Catcher", "SVI", "187", "Common", "Trainer"),
                ("Potion", "SVI", "188", "Common", "Trainer"), ("Rare Candy", "SVI", "191", "Common", "Trainer"),
                ("Switch", "SVI", "194", "Common", "Trainer")
            ],
            "Uncommon": [
                ("Heracross", "SVI", "002", "Uncommon", "Pokémon"), ("Breloom", "SVI", "004", "Uncommon", "Pokémon"),
                ("Cacturne", "SVI", "006", "Uncommon", "Pokémon"), ("Vivillon", "SVI", "010", "Uncommon", "Pokémon"),
                ("Floragato", "SVI", "014", "Uncommon", "Pokémon"), ("Toedscruel", "SVI", "026", "Uncommon", "Pokémon"),
                ("Scovillain", "SVI", "029", "Uncommon", "Pokémon"), ("Torkoal", "SVI", "035", "Uncommon", "Pokémon"),
                ("Crocalor", "SVI", "037", "Uncommon", "Pokémon"), ("Floatzel", "SVI", "047", "Uncommon", "Pokémon"),
                ("Quaxwell", "SVI", "053", "Uncommon", "Pokémon"), ("Wugtrio", "SVI", "057", "Uncommon", "Pokémon"),
                ("Cetitan", "SVI", "060", "Uncommon", "Pokémon"), ("Tatsugiri", "SVI", "062", "Uncommon", "Pokémon"),
                ("Flaaffy", "SVI", "067", "Uncommon", "Pokémon"), ("Pachirisu", "SVI", "068", "Uncommon", "Pokémon"),
                ("Toxtricity", "SVI", "072", "Uncommon", "Pokémon"), ("Kilowattrel", "SVI", "079", "Uncommon", "Pokémon"),
                ("Hypno", "SVI", "083", "Uncommon", "Pokémon"), ("Drifblim", "SVI", "090", "Uncommon", "Pokémon"),
                ("Florges", "SVI", "093", "Uncommon", "Pokémon"), ("Dachsbun", "SVI", "099", "Uncommon", "Pokémon"),
                ("Espathra", "SVI", "103", "Uncommon", "Pokémon"), ("Medicham", "SVI", "111", "Uncommon", "Pokémon"),
                ("Lucario", "SVI", "114", "Uncommon", "Pokémon"), ("Krookodile", "SVI", "117", "Uncommon", "Pokémon"),
                ("Sandaconda", "SVI", "120", "Uncommon", "Pokémon"), ("Stonjourner", "SVI", "121", "Uncommon", "Pokémon"),
                ("Muk", "SVI", "127", "Uncommon", "Pokémon"), ("Spiritomb", "SVI", "129", "Uncommon", "Pokémon"),
                ("Mabosstiff", "SVI", "137", "Uncommon", "Pokémon"), ("Bombirdier", "SVI", "138", "Uncommon", "Pokémon"),
                ("Forretress", "SVI", "139", "Uncommon", "Pokémon"), ("Blissey", "SVI", "145", "Uncommon", "Pokémon"),
                ("Zangoose", "SVI", "147", "Uncommon", "Pokémon"), ("Staraptor", "SVI", "150", "Uncommon", "Pokémon"),
                ("Greedent", "SVI", "152", "Uncommon", "Pokémon"), ("Oinkologne", "SVI", "157", "Uncommon", "Pokémon"),
                ("Maushold", "SVI", "161", "Uncommon", "Pokémon"), ("Cyclizar", "SVI", "163", "Uncommon", "Pokémon"),
                ("Flamigo", "SVI", "165", "Uncommon", "Pokémon"), ("Arven", "SVI", "166", "Uncommon", "Trainer"),
                ("Beach Court", "SVI", "167", "Uncommon", "Trainer"), ("Defiance Band", "SVI", "169", "Uncommon", "Trainer"),
                ("Electric Generator", "SVI", "170", "Uncommon", "Trainer"), ("Exp. Share", "SVI", "174", "Uncommon", "Trainer"),
                ("Jacq", "SVI", "175", "Uncommon", "Trainer"), ("Judge", "SVI", "176", "Uncommon", "Trainer"),
                ("Katy", "SVI", "177", "Uncommon", "Trainer"), ("Mesagoza", "SVI", "178", "Uncommon", "Trainer"),
                ("Miriam", "SVI", "179", "Uncommon", "Trainer"), ("Nest Ball", "SVI", "181", "Uncommon", "Trainer"),
                ("Penny", "SVI", "183", "Uncommon", "Trainer"), ("Picnic Basket", "SVI", "184", "Uncommon", "Trainer"),
                ("Rock Chestplate", "SVI", "192", "Uncommon", "Trainer"), ("Rocky Helmet", "SVI", "193", "Uncommon", "Trainer"),
                ("Team Star Grunt", "SVI", "195", "Uncommon", "Trainer"), ("Ultra Ball", "SVI", "196", "Uncommon", "Trainer"),
                ("Vitality Band", "SVI", "197", "Uncommon", "Trainer"), ("Youngster", "SVI", "198", "Uncommon", "Trainer")
            ],
            "Rare": [
                ("Meowscarada", "SVI", "015", "Rare", "Pokémon"), ("Arboliva", "SVI", "023", "Rare", "Pokémon"),
                ("Skeledirge", "SVI", "038", "Rare", "Pokémon"), ("Armarouge", "SVI", "041", "Rare", "Pokémon"),
                ("Slowbro", "SVI", "043", "Rare", "Pokémon"), ("Quaquaval", "SVI", "054", "Rare", "Pokémon"),
                ("Dondozo", "SVI", "061", "Rare", "Pokémon"), ("Pawmot", "SVI", "076", "Rare", "Pokémon"),
                ("Miraidon", "SVI", "080", "Rare", "Pokémon"), ("Klefki", "SVI", "096", "Rare", "Pokémon"),
                ("Houndstone", "SVI", "106", "Rare", "Pokémon"), ("Annihilape", "SVI", "109", "Rare", "Pokémon"),
                ("Hawlucha", "SVI", "118", "Rare", "Pokémon"), ("Klawf", "SVI", "122", "Rare", "Pokémon"),
                ("Koraidon", "SVI", "124", "Rare", "Pokémon"), ("Kingambit", "SVI", "134", "Rare", "Pokémon"),
                ("Revavroom", "SVI", "142", "Rare", "Pokémon"), ("Indeedee", "SVI", "153", "Rare", "Pokémon"),
                ("Cyclizar", "SVI", "164", "Rare", "Pokémon"), ("Professor’s Research", "SVI", "189", "Rare", "Trainer"),
                ("Professor’s Research", "SVI", "190", "Rare", "Trainer")
            ],
            "Double Rare": [
                ("Spidops ex", "SVI", "019", "Double Rare", "Pokémon"), ("Arcanine ex", "SVI", "032", "Double Rare", "Pokémon"),
                ("Gyarados ex", "SVI", "045", "Double Rare", "Pokémon"), ("Magnezone ex", "SVI", "065", "Double Rare", "Pokémon"),
                ("Miraidon ex", "SVI", "081", "Double Rare", "Pokémon"), ("Gardevoir ex", "SVI", "086", "Double Rare", "Pokémon"),
                ("Banette ex", "SVI", "088", "Double Rare", "Pokémon"), ("Great Tusk ex", "SVI", "123", "Double Rare", "Pokémon"),
                ("Koraidon ex", "SVI", "125", "Double Rare", "Pokémon"), ("Toxicroak ex", "SVI", "131", "Double Rare", "Pokémon"),
                ("Iron Treads ex", "SVI", "143", "Double Rare", "Pokémon"), ("Oinkologne ex", "SVI", "158", "Double Rare", "Pokémon")
            ],
            "Illustration Rare": [
                ("Tarountula", "SVI", "199", "Illustration Rare", "Pokémon"), ("Dolliv", "SVI", "200", "Illustration Rare", "Pokémon"),
                ("Toedscool", "SVI", "201", "Illustration Rare", "Pokémon"), ("Scovillain", "SVI", "202", "Illustration Rare", "Pokémon"),
                ("Armarouge", "SVI", "203", "Illustration Rare", "Pokémon"), ("Slowpoke", "SVI", "204", "Illustration Rare", "Pokémon"),
                ("Clauncher", "SVI", "205", "Illustration Rare", "Pokémon"), ("Wiglett", "SVI", "206", "Illustration Rare", "Pokémon"),
                ("Dondozo", "SVI", "207", "Illustration Rare", "Pokémon"), ("Pachirisu", "SVI", "208", "Illustration Rare", "Pokémon"),
                ("Pawmot", "SVI", "209", "Illustration Rare", "Pokémon"), ("Drowzee", "SVI", "210", "Illustration Rare", "Pokémon"),
                ("Ralts", "SVI", "211", "Illustration Rare", "Pokémon"), ("Kirlia", "SVI", "212", "Illustration Rare", "Pokémon"),
                ("Fidough", "SVI", "213", "Illustration Rare", "Pokémon"), ("Greavard", "SVI", "214", "Illustration Rare", "Pokémon"),
                ("Riolu", "SVI", "215", "Illustration Rare", "Pokémon"), ("Sandile", "SVI", "216", "Illustration Rare", "Pokémon"),
                ("Klawf", "SVI", "217", "Illustration Rare", "Pokémon"), ("Mabosstiff", "SVI", "218", "Illustration Rare", "Pokémon"),
                ("Bombirdier", "SVI", "219", "Illustration Rare", "Pokémon"), ("Kingambit", "SVI", "220", "Illustration Rare", "Pokémon"),
                ("Starly", "SVI", "221", "Illustration Rare", "Pokémon"), ("Skwovet", "SVI", "222", "Illustration Rare", "Pokémon")
            ],
            "Ultra Rare": [
                ("Spidops ex", "SVI", "223", "Ultra Rare", "Pokémon"), ("Arcanine ex", "SVI", "224", "Ultra Rare", "Pokémon"),
                ("Gyarados ex", "SVI", "225", "Ultra Rare", "Pokémon"), ("Magnezone ex", "SVI", "226", "Ultra Rare", "Pokémon"),
                ("Miraidon ex", "SVI", "227", "Ultra Rare", "Pokémon"), ("Gardevoir ex", "SVI", "228", "Ultra Rare", "Pokémon"),
                ("Banette ex", "SVI", "229", "Ultra Rare", "Pokémon"), ("Great Tusk ex", "SVI", "230", "Ultra Rare", "Pokémon"),
                ("Koraidon ex", "SVI", "231", "Ultra Rare", "Pokémon"), ("Toxicroak ex", "SVI", "232", "Ultra Rare", "Pokémon"),
                ("Iron Treads ex", "SVI", "233", "Ultra Rare", "Pokémon"), ("Oinkologne ex", "SVI", "234", "Ultra Rare", "Pokémon"),
                ("Arven", "SVI", "235", "Ultra Rare", "Trainer"), ("Jacq", "SVI", "236", "Ultra Rare", "Trainer"),
                ("Katy", "SVI", "237", "Ultra Rare", "Trainer"), ("Miriam", "SVI", "238", "Ultra Rare", "Trainer"),
                ("Penny", "SVI", "239", "Ultra Rare", "Trainer"), ("Professor’s Research", "SVI", "240", "Ultra Rare", "Trainer"),
                ("Professor’s Research", "SVI", "241", "Ultra Rare", "Trainer"), ("Team Star Grunt", "SVI", "242", "Ultra Rare", "Trainer")
            ],
            "Special Illustration Rare": [
                ("Spidops ex", "SVI", "243", "Special Illustration Rare", "Pokémon"), ("Miraidon ex", "SVI", "244", "Special Illustration Rare", "Pokémon"),
                ("Gardevoir ex", "SVI", "245", "Special Illustration Rare", "Pokémon"), ("Great Tusk ex", "SVI", "246", "Special Illustration Rare", "Pokémon"),
                ("Koraidon ex", "SVI", "247", "Special Illustration Rare", "Pokémon"), ("Iron Treads ex", "SVI", "248", "Special Illustration Rare", "Pokémon"),
                ("Arven", "SVI", "249", "Special Illustration Rare", "Trainer"), ("Jacq", "SVI", "250", "Special Illustration Rare", "Trainer"),
                ("Miriam", "SVI", "251", "Special Illustration Rare", "Trainer"), ("Penny", "SVI", "252", "Special Illustration Rare", "Trainer")
            ],
            "Hyper Rare": [
                ("Miraidon ex", "SVI", "253", "Hyper Rare", "Pokémon"), ("Koraidon ex", "SVI", "254", "Hyper Rare", "Pokémon"),
                ("Nest Ball", "SVI", "255", "Hyper Rare", "Trainer"), ("Rare Candy", "SVI", "256", "Hyper Rare", "Trainer"),
                ("Basic Lightning Energy", "SVI", "257", "Hyper Rare", "Energy"), ("Basic Fighting Energy", "SVI", "258", "Hyper Rare", "Energy")
            ]
        }
    }
}