SV10 = {
    "Destined Rivals": {
        "pull_rates": {
            'P_DR': 1/5, 'P_UR': 1/16, 'P_SIR': 1/94, 'P_HR': 1/149, 'P_IR': 1/12,
        },
        "card_database": {
            "Common": [
                ("Yanma", "DRI", "002", "Common", "Pokémon"), ("Pineco", "DRI", "004", "Common", "Pokémon"),
                ("Shroomish", "DRI", "005", "Common", "Pokémon"), ("Breloom", "DRI", "006", "Common", "Pokémon"),
                ("Cynthia's Roselia", "DRI", "007", "Common", "Pokémon"), ("Mow Rotom", "DRI", "009", "Common", "Pokémon"),
                ("Dwebble", "DRI", "011", "Common", "Pokémon"), ("Fomantis", "DRI", "013", "Common", "Pokémon"),
                ("Team Rocket's Blipbug", "DRI", "015", "Common", "Pokémon"), ("Applin", "DRI", "016", "Common", "Pokémon"),
                ("Dipplin", "DRI", "017", "Common", "Pokémon"), ("Team Rocket's Tarountula", "DRI", "019", "Common", "Pokémon"),
                ("Smoliv", "DRI", "021", "Common", "Pokémon"), ("Dolliv", "DRI", "022", "Common", "Pokémon"),
                ("Rellor", "DRI", "024", "Common", "Pokémon"), ("Growlithe", "DRI", "027", "Common", "Pokémon"),
                ("Ponyta", "DRI", "029", "Common", "Pokémon"), ("Ethan's Cyndaquil", "DRI", "032", "Common", "Pokémon"),
                ("Ethan's Quilava", "DRI", "033", "Common", "Pokémon"), ("Ethan's Slugma", "DRI", "035", "Common", "Pokémon"),
                ("Team Rocket's Houndour", "DRI", "037", "Common", "Pokémon"), ("Torchic", "DRI", "040", "Common", "Pokémon"),
                ("Combusken", "DRI", "041", "Common", "Pokémon"), ("Heat Rotom", "DRI", "043", "Common", "Pokémon"),
                ("Misty's Staryu", "DRI", "046", "Common", "Pokémon"), ("Misty's Magikarp", "DRI", "048", "Common", "Pokémon"),
                ("Misty's Lapras", "DRI", "050", "Common", "Pokémon"), ("Cynthia's Feebas", "DRI", "052", "Common", "Pokémon"),
                ("Clamperl", "DRI", "054", "Common", "Pokémon"), ("Buizel", "DRI", "057", "Common", "Pokémon"),
                ("Snover", "DRI", "059", "Common", "Pokémon"), ("Wash Rotom", "DRI", "061", "Common", "Pokémon"),
                ("Arrokuda", "DRI", "062", "Common", "Pokémon"), ("Cetoddle", "DRI", "064", "Common", "Pokémon"),
                ("Electabuzz", "DRI", "068", "Common", "Pokémon"), ("Ethan's Pichu", "DRI", "071", "Common", "Pokémon"),
                ("Team Rocket's Mareep", "DRI", "072", "Common", "Pokémon"), ("Team Rocket's Flaaffy", "DRI", "073", "Common", "Pokémon"),
                ("Electrike", "DRI", "075", "Common", "Pokémon"), ("Rotom", "DRI", "077", "Common", "Pokémon"),
                ("Team Rocket's Drowzee", "DRI", "079", "Common", "Pokémon"), ("Steven's Baltoy", "DRI", "083", "Common", "Pokémon"),
                ("Team Rocket's Chingling", "DRI", "085", "Common", "Pokémon"), ("Steven's Carbink", "DRI", "086", "Common", "Pokémon"),
                ("Team Rocket's Dottler", "DRI", "088", "Common", "Pokémon"), ("Mankey", "DRI", "090", "Common", "Pokémon"),
                ("Primeape", "DRI", "091", "Common", "Pokémon"), ("Ethan's Sudowoodo", "DRI", "093", "Common", "Pokémon"),
                ("Team Rocket's Larvitar", "DRI", "094", "Common", "Pokémon"), ("Team Rocket's Pupitar", "DRI", "095", "Common", "Pokémon"),
                ("Nosepass", "DRI", "097", "Common", "Pokémon"), ("Meditite", "DRI", "099", "Common", "Pokémon"),
                ("Cynthia's Gible", "DRI", "102", "Common", "Pokémon"), ("Cynthia's Gabite", "DRI", "103", "Common", "Pokémon"),
                ("Hippopotas", "DRI", "105", "Common", "Pokémon"), ("Mudbray", "DRI", "107", "Common", "Pokémon"),
                ("Arven's Toedscool", "DRI", "109", "Common", "Pokémon"), ("Team Rocket's Ekans", "DRI", "112", "Common", "Pokémon"),
                ("Team Rocket's Nidoran♀", "DRI", "114", "Common", "Pokémon"), ("Team Rocket's Nidorina", "DRI", "115", "Common", "Pokémon"),
                ("Team Rocket's Nidoran♂", "DRI", "117", "Common", "Pokémon"), ("Team Rocket's Nidorino", "DRI", "118", "Common", "Pokémon"),
                ("Team Rocket's Zubat", "DRI", "120", "Common", "Pokémon"), ("Team Rocket's Grimer", "DRI", "123", "Common", "Pokémon"),
                ("Team Rocket's Koffing", "DRI", "125", "Common", "Pokémon"), ("Marnie's Purrloin", "DRI", "130", "Common", "Pokémon"),
                ("Marnie's Scraggy", "DRI", "132", "Common", "Pokémon"), ("Marnie's Impidimp", "DRI", "134", "Common", "Pokémon"),
                ("Marnie's Morpeko", "DRI", "137", "Common", "Pokémon"), ("Arven's Maschiff", "DRI", "138", "Common", "Pokémon"),
                ("Skarmory", "DRI", "141", "Common", "Pokémon"), ("Steven's Skarmory", "DRI", "142", "Common", "Pokémon"),
                ("Steven's Beldum", "DRI", "143", "Common", "Pokémon"), ("Team Rocket's Rattata", "DRI", "147", "Common", "Pokémon"),
                ("Team Rocket's Raticate", "DRI", "148", "Common", "Pokémon"), ("Team Rocket's Meowth", "DRI", "149", "Common", "Pokémon"),
                ("Kangaskhan", "DRI", "151", "Common", "Pokémon"), ("Tauros", "DRI", "152", "Common", "Pokémon"),
                ("Team Rocket's Porygon", "DRI", "153", "Common", "Pokémon"), ("Team Rocket's Porygon2", "DRI", "154", "Common", "Pokémon"),
                ("Taillow", "DRI", "156", "Common", "Pokémon"), ("Swellow", "DRI", "157", "Common", "Pokémon"),
                ("Arven's Skwovet", "DRI", "158", "Common", "Pokémon"), ("Squawkabilly", "DRI", "160", "Common", "Pokémon"),
                ("Emcee's Hype", "DRI", "163", "Common", "Trainer")
            ],
            "Uncommon": [
                ("Ethan's Pinsir", "DRI", "001", "Uncommon", "Pokémon"), ("Shaymin", "DRI", "010", "Uncommon", "Pokémon"),
                ("Lurantis", "DRI", "014", "Uncommon", "Pokémon"), ("Teal Mask Ogerpon", "DRI", "026", "Uncommon", "Pokémon"),
                ("Arcanine", "DRI", "028", "Uncommon", "Pokémon"), ("Rapidash", "DRI", "030", "Uncommon", "Pokémon"),
                ("Team Rocket's Houndoom", "DRI", "038", "Uncommon", "Pokémon"), ("Hearthflame Mask Ogerpon", "DRI", "044", "Uncommon", "Pokémon"),
                ("Misty's Psyduck", "DRI", "045", "Uncommon", "Pokémon"), ("Misty's Starmie", "DRI", "047", "Uncommon", "Pokémon"),
                ("Cynthia's Milotic", "DRI", "053", "Uncommon", "Pokémon"), ("Huntail", "DRI", "055", "Uncommon", "Pokémon"),
                ("Floatzel", "DRI", "058", "Uncommon", "Pokémon"), ("Abomasnow", "DRI", "059", "Uncommon", "Pokémon"),
                ("Barraskewda", "DRI", "063", "Uncommon", "Pokémon"), ("Wellspring Mask Ogerpon", "DRI", "067", "Uncommon", "Pokémon"),
                ("Team Rocket's Ampharos", "DRI", "074", "Uncommon", "Pokémon"), ("Manectric", "DRI", "076", "Uncommon", "Pokémon"),
                ("Team Rocket's Hypno", "DRI", "080", "Uncommon", "Pokémon"), ("Steven's Claydol", "DRI", "084", "Uncommon", "Pokémon"),
                ("Team Rocket's Mimikyu", "DRI", "087", "Uncommon", "Pokémon"), ("Team Rocket's Orbeetle", "DRI", "089", "Uncommon", "Pokémon"),
                ("Probopass", "DRI", "098", "Uncommon", "Pokémon"), ("Medicham", "DRI", "100", "Uncommon", "Pokémon"),
                ("Hippowdon", "DRI", "106", "Uncommon", "Pokémon"), ("Mudsdale", "DRI", "108", "Uncommon", "Pokémon"),
                ("Arven's Toedscruel", "DRI", "110", "Uncommon", "Pokémon"), ("Cornerstone Mask Ogerpon", "DRI", "111", "Uncommon", "Pokémon"),
                ("Team Rocket's Arbok", "DRI", "113", "Uncommon", "Pokémon"), ("Team Rocket's Nidoqueen", "DRI", "116", "Uncommon", "Pokémon"),
                ("Team Rocket's Golbat", "DRI", "121", "Uncommon", "Pokémon"), ("Team Rocket's Muk", "DRI", "124", "Uncommon", "Pokémon"),
                ("Team Rocket's Weezing", "DRI", "126", "Uncommon", "Pokémon"), ("Team Rocket's Murkrow", "DRI", "127", "Uncommon", "Pokémon"),
                ("Cynthia's Spiritomb", "DRI", "129", "Uncommon", "Pokémon"), ("Marnie's Liepard", "DRI", "131", "Uncommon", "Pokémon"),
                ("Marnie's Scrafty", "DRI", "133", "Uncommon", "Pokémon"), ("Marnie's Morgrem", "DRI", "135", "Uncommon", "Pokémon"),
                ("Forretress", "DRI", "140", "Uncommon", "Pokémon"), ("Steven's Metang", "DRI", "144", "Uncommon", "Pokémon"),
                ("Team Rocket's Porygon-Z", "DRI", "155", "Uncommon", "Pokémon"), ("Arven's Sandwich", "DRI", "161", "Uncommon", "Trainer"),
                ("Cynthia's Power Weight", "DRI", "162", "Uncommon", "Trainer"), ("Energy Recycler", "DRI", "164", "Uncommon", "Trainer"),
                ("Ethan's Adventure", "DRI", "165", "Uncommon", "Trainer"), ("Granite Cave", "DRI", "166", "Uncommon", "Trainer"),
                ("Judge", "DRI", "167", "Uncommon", "Trainer"), ("Sacred Ash", "DRI", "168", "Uncommon", "Trainer"),
                ("Spikemuth Gym", "DRI", "169", "Uncommon", "Trainer"), ("Team Rocket's Archer", "DRI", "170", "Uncommon", "Trainer"),
                ("Team Rocket's Ariana", "DRI", "171", "Uncommon", "Trainer"), ("Team Rocket's Bother-Bot", "DRI", "172", "Uncommon", "Trainer"),
                ("Team Rocket's Factory", "DRI", "173", "Uncommon", "Trainer"), ("Team Rocket's Giovanni", "DRI", "174", "Uncommon", "Trainer"),
                ("Team Rocket's Great Ball", "DRI", "175", "Uncommon", "Trainer"), ("Team Rocket's Petrel", "DRI", "176", "Uncommon", "Trainer"),
                ("Team Rocket's Proton", "DRI", "177", "Uncommon", "Trainer"), ("Team Rocket's Transceiver", "DRI", "178", "Uncommon", "Trainer"),
                ("Team Rocket's Venture Bomb", "DRI", "179", "Uncommon", "Trainer"), ("Team Rocket's Watchtower", "DRI", "180", "Uncommon", "Trainer"),
                ("TM Machine", "DRI", "181", "Uncommon", "Trainer"), ("Team Rocket's Energy", "DRI", "182", "Uncommon", "Energy")
            ],
            "Rare": [
                ("Cynthia's Roserade", "DRI", "008", "Rare", "Pokémon"), ("Crustle", "DRI", "012", "Rare", "Pokémon"),
                ("Hydrapple", "DRI", "018", "Rare", "Pokémon"), ("Team Rocket's Spidops", "DRI", "020", "Rare", "Pokémon"),
                ("Ethan's Typhlosion", "DRI", "034", "Rare", "Pokémon"), ("Ethan's Magcargo", "DRI", "036", "Rare", "Pokémon"),
                ("Blaziken", "DRI", "042", "Rare", "Pokémon"), ("Misty's Gyarados", "DRI", "049", "Rare", "Pokémon"),
                ("Team Rocket's Articuno", "DRI", "051", "Rare", "Pokémon"), ("Gorebyss", "DRI", "056", "Rare", "Pokémon"),
                ("Team Rocket's Zapdos", "DRI", "070", "Rare", "Pokémon"), ("Zeraora", "DRI", "078", "Rare", "Pokémon"),
                ("Team Rocket's Wobbuffet", "DRI", "082", "Rare", "Pokémon"), ("Annihilape", "DRI", "092", "Rare", "Pokémon"),
                ("Team Rocket's Tyranitar", "DRI", "096", "Rare", "Pokémon"), ("Team Rocket's Sneasel", "DRI", "128", "Rare", "Pokémon"),
                ("Zamazenta", "DRI", "146", "Rare", "Pokémon"), ("Arven's Greedent", "DRI", "159", "Rare", "Pokémon")
            ],
            "Holo Rare": [],
            "Double Rare": [
                ("Yanmega ex", "DRI", "003", "Double Rare", "Pokémon"), ("Arboliva ex", "DRI", "023", "Double Rare", "Pokémon"),
                ("Rabsca ex", "DRI", "025", "Double Rare", "Pokémon"), ("Team Rocket's Moltres ex", "DRI", "031", "Double Rare", "Pokémon"),
                ("Ethan's Ho-Oh ex", "DRI", "039", "Double Rare", "Pokémon"), ("Cetitan ex", "DRI", "065", "Double Rare", "Pokémon"),
                ("Dondozo ex", "DRI", "066", "Double Rare", "Pokémon"), ("Electivire ex", "DRI", "069", "Double Rare", "Pokémon"),
                ("Team Rocket's Mewtwo ex", "DRI", "081", "Double Rare", "Pokémon"), ("Regirock ex", "DRI", "101", "Double Rare", "Pokémon"),
                ("Cynthia's Garchomp ex", "DRI", "104", "Double Rare", "Pokémon"), ("Team Rocket's Nidoking ex", "DRI", "119", "Double Rare", "Pokémon"),
                ("Team Rocket's Crobat ex", "DRI", "122", "Double Rare", "Pokémon"), ("Marnie's Grimmsnarl ex", "DRI", "136", "Double Rare", "Pokémon"),
                ("Arven's Mabosstiff ex", "DRI", "139", "Double Rare", "Pokémon"), ("Steven's Metagross ex", "DRI", "145", "Double Rare", "Pokémon"),
                ("Team Rocket's Persian ex", "DRI", "150", "Double Rare", "Pokémon")
            ],
            "Illustration Rare": [
                ("Yanma", "DRI", "183", "Illustration Rare", "Pokémon"), ("Cynthia's Roserade", "DRI", "184", "Illustration Rare", "Pokémon"),
                ("Shaymin", "DRI", "185", "Illustration Rare", "Pokémon"), ("Crustle", "DRI", "186", "Illustration Rare", "Pokémon"),
                ("Team Rocket's Spidops", "DRI", "187", "Illustration Rare", "Pokémon"), ("Hydrapple", "DRI", "188", "Illustration Rare", "Pokémon"),
                ("Rapidash", "DRI", "189", "Illustration Rare", "Pokémon"), ("Ethan's Typhlosion", "DRI", "190", "Illustration Rare", "Pokémon"),
                ("Team Rocket's Houndoom", "DRI", "191", "Illustration Rare", "Pokémon"), ("Blaziken", "DRI", "192", "Illustration Rare", "Pokémon"),
                ("Misty's Psyduck", "DRI", "193", "Illustration Rare", "Pokémon"), ("Misty's Lapras", "DRI", "194", "Illustration Rare", "Pokémon"),
                ("Clamperl", "DRI", "195", "Illustration Rare", "Pokémon"), ("Electrike", "DRI", "196", "Illustration Rare", "Pokémon"),
                ("Rotom", "DRI", "197", "Illustration Rare", "Pokémon"), ("Team Rocket's Orbeetle", "DRI", "198", "Illustration Rare", "Pokémon"),
                ("Team Rocket's Weezing", "DRI", "199", "Illustration Rare", "Pokémon"), ("Team Rocket's Murkrow", "DRI", "200", "Illustration Rare", "Pokémon"),
                ("Zamazenta", "DRI", "201", "Illustration Rare", "Pokémon"), ("Team Rocket's Raticate", "DRI", "202", "Illustration Rare", "Pokémon"),
                ("Team Rocket's Meowth", "DRI", "203", "Illustration Rare", "Pokémon"), ("Kangaskhan", "DRI", "204", "Illustration Rare", "Pokémon"),
                ("Arven's Greedent", "DRI", "205", "Illustration Rare", "Pokémon")
            ],
            "Ultra Rare": [
                ("Yanmega ex", "DRI", "206", "Ultra Rare", "Pokémon"), ("Arboliva ex", "DRI", "207", "Ultra Rare", "Pokémon"),
                ("Team Rocket's Moltres ex", "DRI", "208", "Ultra Rare", "Pokémon"), ("Ethan's Ho-Oh ex", "DRI", "209", "Ultra Rare", "Pokémon"),
                ("Cetitan ex", "DRI", "210", "Ultra Rare", "Pokémon"), ("Dondozo ex", "DRI", "211", "Ultra Rare", "Pokémon"),
                ("Electivire ex", "DRI", "212", "Ultra Rare", "Pokémon"), ("Team Rocket's Mewtwo ex", "DRI", "213", "Ultra Rare", "Pokémon"),
                ("Regirock ex", "DRI", "214", "Ultra Rare", "Pokémon"), ("Cynthia's Garchomp ex", "DRI", "215", "Ultra Rare", "Pokémon"),
                ("Team Rocket's Nidoking ex", "DRI", "216", "Ultra Rare", "Pokémon"), ("Team Rocket's Crobat ex", "DRI", "217", "Ultra Rare", "Pokémon"),
                ("Arven's Mabosstiff ex", "DRI", "218", "Ultra Rare", "Pokémon"), ("Team Rocket's Persian ex", "DRI", "219", "Ultra Rare", "Pokémon"),
                ("Emcee's Hype", "DRI", "220", "Ultra Rare", "Trainer"), ("Ethan's Adventure", "DRI", "221", "Ultra Rare", "Trainer"),
                ("Judge", "DRI", "222", "Ultra Rare", "Trainer"), ("Team Rocket's Archer", "DRI", "223", "Ultra Rare", "Trainer"),
                ("Team Rocket's Ariana", "DRI", "224", "Ultra Rare", "Trainer"), ("Team Rocket's Giovanni", "DRI", "225", "Ultra Rare", "Trainer"),
                ("Team Rocket's Petrel", "DRI", "226", "Ultra Rare", "Trainer"), ("Team Rocket's Proton", "DRI", "227", "Ultra Rare", "Trainer")
            ],
            "Special Illustration Rare": [
                ("Yanmega ex", "DRI", "228", "Special Illustration Rare", "Pokémon"), ("Team Rocket's Moltres ex", "DRI", "229", "Special Illustration Rare", "Pokémon"),
                ("Ethan's Ho-Oh ex", "DRI", "230", "Special Illustration Rare", "Pokémon"), ("Team Rocket's Mewtwo ex", "DRI", "231", "Special Illustration Rare", "Pokémon"),
                ("Cynthia's Garchomp ex", "DRI", "232", "Special Illustration Rare", "Pokémon"), ("Team Rocket's Nidoking ex", "DRI", "233", "Special Illustration Rare", "Pokémon"),
                ("Team Rocket's Crobat ex", "DRI", "234", "Special Illustration Rare", "Pokémon"), ("Arven's Mabosstiff ex", "DRI", "235", "Special Illustration Rare", "Pokémon"),
                ("Ethan's Adventure", "DRI", "236", "Special Illustration Rare", "Trainer"), ("Team Rocket's Ariana", "DRI", "237", "Special Illustration Rare", "Trainer"),
                ("Team Rocket's Giovanni", "DRI", "238", "Special Illustration Rare", "Trainer")
            ],
            "Hyper Rare": [
                ("Ethan's Ho-Oh ex", "DRI", "239", "Hyper Rare", "Pokémon"), ("Team Rocket's Mewtwo ex", "DRI", "240", "Hyper Rare", "Pokémon"),
                ("Cynthia's Garchomp ex", "DRI", "241", "Hyper Rare", "Pokémon"), ("Team Rocket's Crobat ex", "DRI", "242", "Hyper Rare", "Pokémon"),
                ("Jamming Tower", "DRI", "243", "Hyper Rare", "Trainer"), ("Levincia", "DRI", "244", "Hyper Rare", "Trainer")
            ]
        }
    }
}