SV2 = {
    "Paldea Evolved": {
        "pull_rates": {
            "P_DR": 1/7, "P_IR": 1/13, "P_UR": 1/15, "P_SIR": 1/31, "P_HR": 1/53
        },
        "card_database": {
            "Common": [
                ("Hoppip", "PAL", "001", "Common", "Pokémon"), ("Pineco", "PAL", "004", "Common", "Pokémon"),
                ("Tropius", "PAL", "007", "Common", "Pokémon"), ("Combee", "PAL", "008", "Common", "Pokémon"),
                ("Snover", "PAL", "010", "Common", "Pokémon"), ("Sprigatito", "PAL", "012", "Common", "Pokémon"),
                ("Sprigatito", "PAL", "013", "Common", "Pokémon"), ("Tarountula", "PAL", "016", "Common", "Pokémon"),
                ("Tarountula", "PAL", "017", "Common", "Pokémon"), ("Nymble", "PAL", "019", "Common", "Pokémon"),
                ("Nymble", "PAL", "020", "Common", "Pokémon"), ("Bramblin", "PAL", "022", "Common", "Pokémon"),
                ("Bramblin", "PAL", "023", "Common", "Pokémon"), ("Rellor", "PAL", "025", "Common", "Pokémon"),
                ("Rellor", "PAL", "026", "Common", "Pokémon"), ("Litleo", "PAL", "031", "Common", "Pokémon"),
                ("Fuecoco", "PAL", "034", "Common", "Pokémon"), ("Fuecoco", "PAL", "035", "Common", "Pokémon"),
                ("Charcadet", "PAL", "038", "Common", "Pokémon"), ("Charcadet", "PAL", "039", "Common", "Pokémon"),
                ("Magikarp", "PAL", "042", "Common", "Pokémon"), ("Marill", "PAL", "044", "Common", "Pokémon"),
                ("Delibird", "PAL", "046", "Common", "Pokémon"), ("Luvdisc", "PAL", "047", "Common", "Pokémon"),
                ("Quaxly", "PAL", "049", "Common", "Pokémon"), ("Quaxly", "PAL", "050", "Common", "Pokémon"),
                ("Cetoddle", "PAL", "053", "Common", "Pokémon"), ("Cetoddle", "PAL", "054", "Common", "Pokémon"),
                ("Frigibax", "PAL", "057", "Common", "Pokémon"), ("Frigibax", "PAL", "058", "Common", "Pokémon"),
                ("Pikachu", "PAL", "062", "Common", "Pokémon"), ("Magnemite", "PAL", "065", "Common", "Pokémon"),
                ("Voltorb", "PAL", "066", "Common", "Pokémon"), ("Shinx", "PAL", "068", "Common", "Pokémon"),
                ("Shinx", "PAL", "069", "Common", "Pokémon"), ("Pincurchin", "PAL", "072", "Common", "Pokémon"),
                ("Pawmi", "PAL", "074", "Common", "Pokémon"), ("Tadbulb", "PAL", "077", "Common", "Pokémon"),
                ("Tadbulb", "PAL", "078", "Common", "Pokémon"), ("Wattrel", "PAL", "080", "Common", "Pokémon"),
                ("Wattrel", "PAL", "081", "Common", "Pokémon"), ("Jigglypuff", "PAL", "083", "Common", "Pokémon"),
                ("Slowpoke", "PAL", "085", "Common", "Pokémon"), ("Misdreavus", "PAL", "087", "Common", "Pokémon"),
                ("Gothita", "PAL", "090", "Common", "Pokémon"), ("Sandygast", "PAL", "095", "Common", "Pokémon"),
                ("Tinkatink", "PAL", "100", "Common", "Pokémon"), ("Tinkatink", "PAL", "101", "Common", "Pokémon"),
                ("Tinkatink", "PAL", "102", "Common", "Pokémon"), ("Mankey", "PAL", "106", "Common", "Pokémon"),
                ("Larvitar", "PAL", "110", "Common", "Pokémon"), ("Makuhita", "PAL", "112", "Common", "Pokémon"),
                ("Croagunk", "PAL", "114", "Common", "Pokémon"), ("Rockruff", "PAL", "116", "Common", "Pokémon"),
                ("Falinks", "PAL", "119", "Common", "Pokémon"), ("Nacli", "PAL", "120", "Common", "Pokémon"),
                ("Nacli", "PAL", "121", "Common", "Pokémon"), ("Glimmet", "PAL", "124", "Common", "Pokémon"),
                ("Glimmet", "PAL", "125", "Common", "Pokémon"), ("Paldean Wooper", "PAL", "128", "Common", "Pokémon"),
                ("Paldean Wooper", "PAL", "129", "Common", "Pokémon"), ("Murkrow", "PAL", "131", "Common", "Pokémon"),
                ("Sneasel", "PAL", "133", "Common", "Pokémon"), ("Deino", "PAL", "138", "Common", "Pokémon"),
                ("Maschiff", "PAL", "141", "Common", "Pokémon"), ("Maschiff", "PAL", "142", "Common", "Pokémon"),
                ("Shroodle", "PAL", "144", "Common", "Pokémon"), ("Shroodle", "PAL", "145", "Common", "Pokémon"),
                ("Cufant", "PAL", "149", "Common", "Pokémon"), ("Noibat", "PAL", "152", "Common", "Pokémon"),
                ("Girafarig", "PAL", "154", "Common", "Pokémon"), ("Dunsparce", "PAL", "156", "Common", "Pokémon"),
                ("Wingull", "PAL", "158", "Common", "Pokémon"), ("Slakoth", "PAL", "160", "Common", "Pokémon"),
                ("Fletchling", "PAL", "163", "Common", "Pokémon"), ("Rookidee", "PAL", "164", "Common", "Pokémon"),
                ("Tandemaus", "PAL", "166", "Common", "Pokémon"), ("Tandemaus", "PAL", "167", "Common", "Pokémon"),
                ("Clavell", "PAL", "177", "Common", "Trainer"), ("Great Ball", "PAL", "183", "Common", "Trainer"),
                ("Super Rod", "PAL", "188", "Common", "Trainer")
            ],
            "Uncommon": [
                ("Skiploom", "PAL", "002", "Uncommon", "Pokémon"), ("Heracross", "PAL", "006", "Uncommon", "Pokémon"),
                ("Vespiquen", "PAL", "009", "Uncommon", "Pokémon"), ("Floragato", "PAL", "014", "Uncommon", "Pokémon"),
                ("Spidops", "PAL", "018", "Uncommon", "Pokémon"), ("Brambleghast", "PAL", "024", "Uncommon", "Pokémon"),
                ("Paldean Tauros", "PAL", "028", "Uncommon", "Pokémon"), ("Fletchinder", "PAL", "029", "Uncommon", "Pokémon"),
                ("Talonflame", "PAL", "030", "Uncommon", "Pokémon"), ("Pyroar", "PAL", "032", "Uncommon", "Pokémon"),
                ("Crocalor", "PAL", "036", "Uncommon", "Pokémon"), ("Paldean Tauros", "PAL", "041", "Uncommon", "Pokémon"),
                ("Azumarill", "PAL", "045", "Uncommon", "Pokémon"), ("Eiscue", "PAL", "048", "Uncommon", "Pokémon"),
                ("Quaxwell", "PAL", "051", "Uncommon", "Pokémon"), ("Cetitan", "PAL", "055", "Uncommon", "Pokémon"),
                ("Arctibax", "PAL", "059", "Uncommon", "Pokémon"), ("Raichu", "PAL", "064", "Uncommon", "Pokémon"),
                ("Electrode", "PAL", "067", "Uncommon", "Pokémon"), ("Luxio", "PAL", "070", "Uncommon", "Pokémon"),
                ("Pincurchin", "PAL", "073", "Uncommon", "Pokémon"), ("Pawmo", "PAL", "075", "Uncommon", "Pokémon"),
                ("Kilowattrel", "PAL", "082", "Uncommon", "Pokémon"), ("Mismagius", "PAL", "088", "Uncommon", "Pokémon"),
                ("Gothorita", "PAL", "091", "Uncommon", "Pokémon"), ("Gothitelle", "PAL", "092", "Uncommon", "Pokémon"),
                ("Oranguru", "PAL", "094", "Uncommon", "Pokémon"), ("Palossand", "PAL", "096", "Uncommon", "Pokémon"),
                ("Tinkatuff", "PAL", "103", "Uncommon", "Pokémon"), ("Tinkatuff", "PAL", "104", "Uncommon", "Pokémon"),
                ("Primeape", "PAL", "107", "Uncommon", "Pokémon"), ("Paldean Tauros", "PAL", "108", "Uncommon", "Pokémon"),
                ("Sudowoodo", "PAL", "109", "Uncommon", "Pokémon"), ("Pupitar", "PAL", "111", "Uncommon", "Pokémon"),
                ("Toxicroak", "PAL", "115", "Uncommon", "Pokémon"), ("Passimian", "PAL", "118", "Uncommon", "Pokémon"),
                ("Naclstack", "PAL", "122", "Uncommon", "Pokémon"), ("Honchkrow", "PAL", "132", "Uncommon", "Pokémon"),
                ("Seviper", "PAL", "137", "Uncommon", "Pokémon"), ("Zweilous", "PAL", "139", "Uncommon", "Pokémon"),
                ("Mabosstiff", "PAL", "143", "Uncommon", "Pokémon"), ("Grafaiai", "PAL", "146", "Uncommon", "Pokémon"),
                ("Bombirdier", "PAL", "147", "Uncommon", "Pokémon"), ("Corviknight", "PAL", "148", "Uncommon", "Pokémon"),
                ("Farigiraf", "PAL", "155", "Uncommon", "Pokémon"), ("Dudunsparce", "PAL", "157", "Uncommon", "Pokémon"),
                ("Pelipper", "PAL", "159", "Uncommon", "Pokémon"), ("Vigoroth", "PAL", "161", "Uncommon", "Pokémon"),
                ("Corvisquire", "PAL", "165", "Uncommon", "Pokémon"), ("Maushold", "PAL", "168", "Uncommon", "Pokémon"),
                ("Flamigo", "PAL", "170", "Uncommon", "Pokémon"), ("Artazon", "PAL", "171", "Uncommon", "Trainer"),
                ("Bravery Charm", "PAL", "173", "Uncommon", "Trainer"), ("Calamitous Snowy Mountain", "PAL", "174", "Uncommon", "Trainer"),
                ("Calamitous Wasteland", "PAL", "175", "Uncommon", "Trainer"), ("Choice Belt", "PAL", "176", "Uncommon", "Trainer"),
                ("Delivery Drone", "PAL", "178", "Uncommon", "Trainer"), ("Dendra", "PAL", "179", "Uncommon", "Trainer"),
                ("Falkner", "PAL", "180", "Uncommon", "Trainer"), ("Fighting Au Lait", "PAL", "181", "Uncommon", "Trainer"),
                ("Giacomo", "PAL", "182", "Uncommon", "Trainer"), ("Grusha", "PAL", "184", "Uncommon", "Trainer"),
                ("Iono", "PAL", "185", "Uncommon", "Trainer"), ("Practice Studio", "PAL", "186", "Uncommon", "Trainer"),
                ("Saguaro", "PAL", "187", "Uncommon", "Trainer"), ("Superior Energy Retrieval", "PAL", "189", "Uncommon", "Trainer"),
                ("Jet Energy", "PAL", "190", "Uncommon", "Energy"), ("Luminous Energy", "PAL", "191", "Uncommon", "Energy"),
                ("Reversal Energy", "PAL", "192", "Uncommon", "Energy"), ("Therapeutic Energy", "PAL", "193", "Uncommon", "Energy")
            ],
            "Rare": [
                ("Jumpluff", "PAL", "003", "Rare", "Pokémon"), ("Abomasnow", "PAL", "011", "Rare", "Pokémon"),
                ("Lokix", "PAL", "021", "Rare", "Pokémon"), ("Oricorio", "PAL", "033", "Rare", "Pokémon"),
                ("Gyarados", "PAL", "043", "Rare", "Pokémon"), ("Veluza", "PAL", "056", "Rare", "Pokémon"),
                ("Baxcalibur", "PAL", "060", "Rare", "Pokémon"), ("Luxray", "PAL", "071", "Rare", "Pokémon"),
                ("Pawmot", "PAL", "076", "Rare", "Pokémon"), ("Wigglytuff", "PAL", "084", "Rare", "Pokémon"),
                ("Spiritomb", "PAL", "089", "Rare", "Pokémon"), ("Mimikyu", "PAL", "097", "Rare", "Pokémon"),
                ("Ceruledge", "PAL", "098", "Rare", "Pokémon"), ("Rabsca", "PAL", "099", "Rare", "Pokémon"),
                ("Tinkaton", "PAL", "105", "Rare", "Pokémon"), ("Hariyama", "PAL", "113", "Rare", "Pokémon"),
                ("Garganacl", "PAL", "123", "Rare", "Pokémon"), ("Glimmora", "PAL", "126", "Rare", "Pokémon"),
                ("Weavile", "PAL", "134", "Rare", "Pokémon"), ("Tyranitar", "PAL", "135", "Rare", "Pokémon"),
                ("Sableye", "PAL", "136", "Rare", "Pokémon"), ("Hydreigon", "PAL", "140", "Rare", "Pokémon"),
                ("Orthworm", "PAL", "151", "Rare", "Pokémon"), ("Slaking", "PAL", "162", "Rare", "Pokémon"),
                ("Boss’s Orders", "PAL", "172", "Rare", "Trainer")
            ],
            "Double Rare": [
                ("Forretress ex", "PAL", "005", "Double Rare", "Pokémon"), ("Meowscarada ex", "PAL", "015", "Double Rare", "Pokémon"),
                ("Wo-Chien ex", "PAL", "027", "Double Rare", "Pokémon"), ("Skeledirge ex", "PAL", "037", "Double Rare", "Pokémon"),
                ("Chi-Yu ex", "PAL", "040", "Double Rare", "Pokémon"), ("Quaquaval ex", "PAL", "052", "Double Rare", "Pokémon"),
                ("Chien-Pao ex", "PAL", "061", "Double Rare", "Pokémon"), ("Pikachu ex", "PAL", "063", "Double Rare", "Pokémon"),
                ("Bellibolt ex", "PAL", "079", "Double Rare", "Pokémon"), ("Slowking ex", "PAL", "086", "Double Rare", "Pokémon"),
                ("Dedenne ex", "PAL", "093", "Double Rare", "Pokémon"), ("Lycanroc ex", "PAL", "117", "Double Rare", "Pokémon"),
                ("Ting-Lu ex", "PAL", "127", "Double Rare", "Pokémon"), ("Paldean Clodsire ex", "PAL", "130", "Double Rare", "Pokémon"),
                ("Copperajah ex", "PAL", "150", "Double Rare", "Pokémon"), ("Noivern ex", "PAL", "153", "Double Rare", "Pokémon"),
                ("Squawkabilly ex", "PAL", "169", "Double Rare", "Pokémon")
            ],
            "Illustration Rare": [
                ("Heracross", "PAL", "194", "Illustration Rare", "Pokémon"), ("Tropius", "PAL", "195", "Illustration Rare", "Pokémon"),
                ("Sprigatito", "PAL", "196", "Illustration Rare", "Pokémon"), ("Floragato", "PAL", "197", "Illustration Rare", "Pokémon"),
                ("Bramblin", "PAL", "198", "Illustration Rare", "Pokémon"), ("Fletchinder", "PAL", "199", "Illustration Rare", "Pokémon"),
                ("Pyroar", "PAL", "200", "Illustration Rare", "Pokémon"), ("Fuecoco", "PAL", "201", "Illustration Rare", "Pokémon"),
                ("Crocalor", "PAL", "202", "Illustration Rare", "Pokémon"), ("Magikarp", "PAL", "203", "Illustration Rare", "Pokémon"),
                ("Marill", "PAL", "204", "Illustration Rare", "Pokémon"), ("Eiscue", "PAL", "205", "Illustration Rare", "Pokémon"),
                ("Quaxly", "PAL", "206", "Illustration Rare", "Pokémon"), ("Quaxwell", "PAL", "207", "Illustration Rare", "Pokémon"),
                ("Frigibax", "PAL", "208", "Illustration Rare", "Pokémon"), ("Arctibax", "PAL", "209", "Illustration Rare", "Pokémon"),
                ("Baxcalibur", "PAL", "210", "Illustration Rare", "Pokémon"), ("Raichu", "PAL", "211", "Illustration Rare", "Pokémon"),
                ("Mismagius", "PAL", "212", "Illustration Rare", "Pokémon"), ("Gothorita", "PAL", "213", "Illustration Rare", "Pokémon"),
                ("Sandygast", "PAL", "214", "Illustration Rare", "Pokémon"), ("Rabsca", "PAL", "215", "Illustration Rare", "Pokémon"),
                ("Tinkatink", "PAL", "216", "Illustration Rare", "Pokémon"), ("Tinkatuff", "PAL", "217", "Illustration Rare", "Pokémon"),
                ("Paldean Tauros", "PAL", "218", "Illustration Rare", "Pokémon"), ("Sudowoodo", "PAL", "219", "Illustration Rare", "Pokémon"),
                ("Nacli", "PAL", "220", "Illustration Rare", "Pokémon"), ("Paldean Wooper", "PAL", "221", "Illustration Rare", "Pokémon"),
                ("Tyranitar", "PAL", "222", "Illustration Rare", "Pokémon"), ("Grafaiai", "PAL", "223", "Illustration Rare", "Pokémon"),
                ("Orthworm", "PAL", "224", "Illustration Rare", "Pokémon"), ("Rookidee", "PAL", "225", "Illustration Rare", "Pokémon"),
                ("Maushold", "PAL", "226", "Illustration Rare", "Pokémon"), ("Flamigo", "PAL", "227", "Illustration Rare", "Pokémon"),
                ("Farigiraf", "PAL", "228", "Illustration Rare", "Pokémon"), ("Dudunsparce", "PAL", "229", "Illustration Rare", "Pokémon")
            ],
            "Ultra Rare": [
                ("Forretress ex", "PAL", "230", "Ultra Rare", "Pokémon"), ("Meowscarada ex", "PAL", "231", "Ultra Rare", "Pokémon"),
                ("Wo-Chien ex", "PAL", "232", "Ultra Rare", "Pokémon"), ("Skeledirge ex", "PAL", "233", "Ultra Rare", "Pokémon"),
                ("Chi-Yu ex", "PAL", "234", "Ultra Rare", "Pokémon"), ("Quaquaval ex", "PAL", "235", "Ultra Rare", "Pokémon"),
                ("Chien-Pao ex", "PAL", "236", "Ultra Rare", "Pokémon"), ("Bellibolt ex", "PAL", "237", "Ultra Rare", "Pokémon"),
                ("Slowking ex", "PAL", "238", "Ultra Rare", "Pokémon"), ("Dedenne ex", "PAL", "239", "Ultra Rare", "Pokémon"),
                ("Tinkaton ex", "PAL", "240", "Ultra Rare", "Pokémon"), ("Lycanroc ex", "PAL", "241", "Ultra Rare", "Pokémon"),
                ("Annihilape ex", "PAL", "242", "Ultra Rare", "Pokémon"), ("Ting-Lu ex", "PAL", "243", "Ultra Rare", "Pokémon"),
                ("Paldean Clodsire ex", "PAL", "244", "Ultra Rare", "Pokémon"), ("Copperajah ex", "PAL", "245", "Ultra Rare", "Pokémon"),
                ("Noivern ex", "PAL", "246", "Ultra Rare", "Pokémon"), ("Squawkabilly ex", "PAL", "247", "Ultra Rare", "Pokémon"),
                ("Boss’s Orders", "PAL", "248", "Ultra Rare", "Trainer"), ("Clavell", "PAL", "249", "Ultra Rare", "Trainer"),
                ("Dendra", "PAL", "250", "Ultra Rare", "Trainer"), ("Falkner", "PAL", "251", "Ultra Rare", "Trainer"),
                ("Giacomo", "PAL", "252", "Ultra Rare", "Trainer"), ("Grusha", "PAL", "253", "Ultra Rare", "Trainer"),
                ("Iono", "PAL", "254", "Ultra Rare", "Trainer"), ("Saguaro", "PAL", "255", "Ultra Rare", "Trainer")
            ],
            "Special Illustration Rare": [
                ("Meowscarada ex", "PAL", "256", "Special Illustration Rare", "Pokémon"), ("Wo-Chien ex", "PAL", "257", "Special Illustration Rare", "Pokémon"),
                ("Skeledirge ex", "PAL", "258", "Special Illustration Rare", "Pokémon"), ("Chi-Yu ex", "PAL", "259", "Special Illustration Rare", "Pokémon"),
                ("Quaquaval ex", "PAL", "260", "Special Illustration Rare", "Pokémon"), ("Chien-Pao ex", "PAL", "261", "Special Illustration Rare", "Pokémon"),
                ("Tinkaton ex", "PAL", "262", "Special Illustration Rare", "Pokémon"), ("Ting-Lu ex", "PAL", "263", "Special Illustration Rare", "Pokémon"),
                ("Squawkabilly ex", "PAL", "264", "Special Illustration Rare", "Pokémon"), ("Boss’s Orders", "PAL", "265", "Special Illustration Rare", "Trainer"),
                ("Dendra", "PAL", "266", "Special Illustration Rare", "Trainer"), ("Giacomo", "PAL", "267", "Special Illustration Rare", "Trainer"),
                ("Grusha", "PAL", "268", "Special Illustration Rare", "Trainer"), ("Iono", "PAL", "269", "Special Illustration Rare", "Trainer"),
                ("Saguaro", "PAL", "270", "Special Illustration Rare", "Trainer")
            ],
            "Hyper Rare": [
                ("Meowscarada ex", "PAL", "271", "Hyper Rare", "Pokémon"), ("Skeledirge ex", "PAL", "272", "Hyper Rare", "Pokémon"),
                ("Quaquaval ex", "PAL", "273", "Hyper Rare", "Pokémon"), ("Chien-Pao ex", "PAL", "274", "Hyper Rare", "Pokémon"),
                ("Ting-Lu ex", "PAL", "275", "Hyper Rare", "Pokémon"), ("Super Rod", "PAL", "276", "Hyper Rare", "Trainer"),
                ("Superior Energy Retrieval", "PAL", "277", "Hyper Rare", "Trainer"), ("Basic Grass Energy", "PAL", "278", "Hyper Rare", "Energy"),
                ("Basic Water Energy", "PAL", "279", "Hyper Rare", "Energy")
            ]
        }
    }
}