SV3 = {
    "Obsidian Flames": {
        "pull_rates": {
            "P_DR": 1/7, "P_IR": 1/13, "P_UR": 1/15, "P_SIR": 1/32, "P_HR": 1/52
        },
        "card_database": {
            "Common": [
                ("Oddish", "OBF", "001", "Common", "Pokémon"), ("Gloom", "OBF", "002", "Common", "Pokémon"),
                ("Scyther", "OBF", "004", "Common", "Pokémon"), ("Shuckle", "OBF", "005", "Common", "Pokémon"),
                ("Surskit", "OBF", "006", "Common", "Pokémon"), ("Combee", "OBF", "008", "Common", "Pokémon"),
                ("Foongus", "OBF", "009", "Common", "Pokémon"), ("Phantump", "OBF", "011", "Common", "Pokémon"),
                ("Rowlet", "OBF", "013", "Common", "Pokémon"), ("Bounsweet", "OBF", "016", "Common", "Pokémon"),
                ("Steenee", "OBF", "017", "Common", "Pokémon"), ("Smoliv", "OBF", "019", "Common", "Pokémon"),
                ("Dolliv", "OBF", "020", "Common", "Pokémon"), ("Capsakid", "OBF", "023", "Common", "Pokémon"),
                ("Capsakid", "OBF", "024", "Common", "Pokémon"), ("Charmander", "OBF", "026", "Common", "Pokémon"),
                ("Vulpix", "OBF", "028", "Common", "Pokémon"), ("Numel", "OBF", "031", "Common", "Pokémon"),
                ("Darumaka", "OBF", "034", "Common", "Pokémon"), ("Litwick", "OBF", "036", "Common", "Pokémon"),
                ("Lampent", "OBF", "037", "Common", "Pokémon"), ("Heatmor", "OBF", "039", "Common", "Pokémon"),
                ("Larvesta", "OBF", "040", "Common", "Pokémon"), ("Charcadet", "OBF", "043", "Common", "Pokémon"),
                ("Carvanha", "OBF", "046", "Common", "Pokémon"), ("Buizel", "OBF", "048", "Common", "Pokémon"),
                ("Tympole", "OBF", "050", "Common", "Pokémon"), ("Palpitoad", "OBF", "051", "Common", "Pokémon"),
                ("Cubchoo", "OBF", "053", "Common", "Pokémon"), ("Froakie", "OBF", "056", "Common", "Pokémon"),
                ("Wiglett", "OBF", "058", "Common", "Pokémon"), ("Finizen", "OBF", "060", "Common", "Pokémon"),
                ("Finizen", "OBF", "061", "Common", "Pokémon"), ("Magnemite", "OBF", "063", "Common", "Pokémon"),
                ("Magneton", "OBF", "064", "Common", "Pokémon"), ("Tynamo", "OBF", "067", "Common", "Pokémon"),
                ("Eelektrik", "OBF", "068", "Common", "Pokémon"), ("Toxel", "OBF", "071", "Common", "Pokémon"),
                ("Tadbulb", "OBF", "074", "Common", "Pokémon"), ("Tadbulb", "OBF", "075", "Common", "Pokémon"),
                ("Tadbulb", "OBF", "076", "Common", "Pokémon"), ("Cleffa", "OBF", "080", "Common", "Pokémon"),
                ("Clefairy", "OBF", "081", "Common", "Pokémon"), ("Togepi", "OBF", "083", "Common", "Pokémon"),
                ("Snubbull", "OBF", "087", "Common", "Pokémon"), ("Mawile", "OBF", "089", "Common", "Pokémon"),
                ("Spoink", "OBF", "090", "Common", "Pokémon"), ("Baltoy", "OBF", "094", "Common", "Pokémon"),
                ("Sinistea", "OBF", "097", "Common", "Pokémon"), ("Greavard", "OBF", "099", "Common", "Pokémon"),
                ("Greavard", "OBF", "100", "Common", "Pokémon"), ("Diglett", "OBF", "103", "Common", "Pokémon"),
                ("Larvitar", "OBF", "105", "Common", "Pokémon"), ("Nosepass", "OBF", "107", "Common", "Pokémon"),
                ("Barboach", "OBF", "108", "Common", "Pokémon"), ("Bonsly", "OBF", "110", "Common", "Pokémon"),
                ("Drilbur", "OBF", "111", "Common", "Pokémon"), ("Crabrawler", "OBF", "114", "Common", "Pokémon"),
                ("Rockruff", "OBF", "116", "Common", "Pokémon"), ("Toedscool", "OBF", "118", "Common", "Pokémon"),
                ("Glimmet", "OBF", "121", "Common", "Pokémon"), ("Glimmet", "OBF", "122", "Common", "Pokémon"),
                ("Paldean Wooper", "OBF", "126", "Common", "Pokémon"), ("Paldean Wooper", "OBF", "127", "Common", "Pokémon"),
                ("Houndour", "OBF", "131", "Common", "Pokémon"), ("Houndour", "OBF", "132", "Common", "Pokémon"),
                ("Inkay", "OBF", "137", "Common", "Pokémon"), ("Salandit", "OBF", "139", "Common", "Pokémon"),
                ("Bronzor", "OBF", "144", "Common", "Pokémon"), ("Pawniard", "OBF", "148", "Common", "Pokémon"),
                ("Bisharp", "OBF", "149", "Common", "Pokémon"), ("Togedemaru", "OBF", "151", "Common", "Pokémon"),
                ("Meltan", "OBF", "152", "Common", "Pokémon"), ("Varoom", "OBF", "154", "Common", "Pokémon"),
                ("Varoom", "OBF", "155", "Common", "Pokémon"), ("Dratini", "OBF", "157", "Common", "Pokémon"),
                ("Pidgey", "OBF", "162", "Common", "Pokémon"), ("Eevee", "OBF", "166", "Common", "Pokémon"),
                ("Zigzagoon", "OBF", "167", "Common", "Pokémon"), ("Swablu", "OBF", "169", "Common", "Pokémon"),
                ("Lillipup", "OBF", "170", "Common", "Pokémon"), ("Herdier", "OBF", "171", "Common", "Pokémon"),
                ("Audino", "OBF", "173", "Common", "Pokémon"), ("Bunnelby", "OBF", "175", "Common", "Pokémon"),
                ("Yungoos", "OBF", "176", "Common", "Pokémon"), ("Skwovet", "OBF", "178", "Common", "Pokémon"),
                ("Lechonk", "OBF", "180", "Common", "Pokémon"), ("Lechonk", "OBF", "181", "Common", "Pokémon"),
                ("Lechonk", "OBF", "182", "Common", "Pokémon"), ("Ryme", "OBF", "194", "Common", "Trainer"),
                ("Town Store", "OBF", "196", "Common", "Trainer")
            ],
            "Uncommon": [
                ("Bellossom", "OBF", "003", "Uncommon", "Pokémon"), ("Masquerain", "OBF", "007", "Uncommon", "Pokémon"),
                ("Amoonguss", "OBF", "010", "Uncommon", "Pokémon"), ("Trevenant", "OBF", "012", "Uncommon", "Pokémon"),
                ("Dartrix", "OBF", "014", "Uncommon", "Pokémon"), ("Tsareena", "OBF", "018", "Uncommon", "Pokémon"),
                ("Arboliva", "OBF", "021", "Uncommon", "Pokémon"), ("Charmeleon", "OBF", "027", "Uncommon", "Pokémon"),
                ("Ninetales", "OBF", "029", "Uncommon", "Pokémon"), ("Camerupt", "OBF", "032", "Uncommon", "Pokémon"),
                ("Darmanitan", "OBF", "035", "Uncommon", "Pokémon"), ("Chandelure", "OBF", "038", "Uncommon", "Pokémon"),
                ("Volcarona", "OBF", "041", "Uncommon", "Pokémon"), ("Armarouge", "OBF", "044", "Uncommon", "Pokémon"),
                ("Lapras", "OBF", "045", "Uncommon", "Pokémon"), ("Sharpedo", "OBF", "047", "Uncommon", "Pokémon"),
                ("Floatzel", "OBF", "049", "Uncommon", "Pokémon"), ("Seismitoad", "OBF", "052", "Uncommon", "Pokémon"),
                ("Beartic", "OBF", "054", "Uncommon", "Pokémon"), ("Frogadier", "OBF", "057", "Uncommon", "Pokémon"),
                ("Wugtrio", "OBF", "059", "Uncommon", "Pokémon"), ("Magnezone", "OBF", "065", "Uncommon", "Pokémon"),
                ("Eelektross", "OBF", "069", "Uncommon", "Pokémon"), ("Bellibolt", "OBF", "077", "Uncommon", "Pokémon"),
                ("Bellibolt", "OBF", "078", "Uncommon", "Pokémon"), ("Togetic", "OBF", "084", "Uncommon", "Pokémon"),
                ("Espeon", "OBF", "086", "Uncommon", "Pokémon"), ("Granbull", "OBF", "088", "Uncommon", "Pokémon"),
                ("Grumpig", "OBF", "091", "Uncommon", "Pokémon"), ("Lunatone", "OBF", "092", "Uncommon", "Pokémon"),
                ("Solrock", "OBF", "093", "Uncommon", "Pokémon"), ("Polteageist", "OBF", "098", "Uncommon", "Pokémon"),
                ("Houndstone", "OBF", "101", "Uncommon", "Pokémon"), ("Dugtrio", "OBF", "104", "Uncommon", "Pokémon"),
                ("Pupitar", "OBF", "106", "Uncommon", "Pokémon"), ("Whiscash", "OBF", "109", "Uncommon", "Pokémon"),
                ("Stunfisk", "OBF", "112", "Uncommon", "Pokémon"), ("Diggersby", "OBF", "113", "Uncommon", "Pokémon"),
                ("Crabominable", "OBF", "115", "Uncommon", "Pokémon"), ("Lycanroc", "OBF", "117", "Uncommon", "Pokémon"),
                ("Toedscruel", "OBF", "119", "Uncommon", "Pokémon"), ("Paldean Clodsire", "OBF", "128", "Uncommon", "Pokémon"),
                ("Paldean Clodsire", "OBF", "129", "Uncommon", "Pokémon"), ("Umbreon", "OBF", "130", "Uncommon", "Pokémon"),
                ("Houndoom", "OBF", "133", "Uncommon", "Pokémon"), ("Malamar", "OBF", "138", "Uncommon", "Pokémon"),
                ("Salazzle", "OBF", "140", "Uncommon", "Pokémon"), ("Skarmory", "OBF", "142", "Uncommon", "Pokémon"),
                ("Mawile", "OBF", "143", "Uncommon", "Pokémon"), ("Bronzong", "OBF", "145", "Uncommon", "Pokémon"),
                ("Probopass", "OBF", "146", "Uncommon", "Pokémon"), ("Excadrill", "OBF", "147", "Uncommon", "Pokémon"),
                ("Kingambit", "OBF", "150", "Uncommon", "Pokémon"), ("Dragonair", "OBF", "158", "Uncommon", "Pokémon"),
                ("Altaria", "OBF", "160", "Uncommon", "Pokémon"), ("Drampa", "OBF", "161", "Uncommon", "Pokémon"),
                ("Pidgeotto", "OBF", "163", "Uncommon", "Pokémon"), ("Kangaskhan", "OBF", "165", "Uncommon", "Pokémon"),
                ("Linoone", "OBF", "168", "Uncommon", "Pokémon"), ("Stoutland", "OBF", "172", "Uncommon", "Pokémon"),
                ("Bouffalant", "OBF", "174", "Uncommon", "Pokémon"), ("Gumshoos", "OBF", "177", "Uncommon", "Pokémon"),
                ("Oinkologne", "OBF", "183", "Uncommon", "Pokémon"), ("Oinkologne", "OBF", "184", "Uncommon", "Pokémon"),
                ("Flamigo", "OBF", "185", "Uncommon", "Pokémon"), ("Arven", "OBF", "186", "Uncommon", "Trainer"),
                ("Brassius", "OBF", "187", "Uncommon", "Trainer"), ("Letter of Encouragement", "OBF", "189", "Uncommon", "Trainer"),
                ("Ortega", "OBF", "190", "Uncommon", "Trainer"), ("Patrol Cap", "OBF", "191", "Uncommon", "Trainer"),
                ("Pokémon League Headquarters", "OBF", "192", "Uncommon", "Trainer"), ("Poppy", "OBF", "193", "Uncommon", "Trainer"),
                ("Team Star Grunt", "OBF", "195", "Uncommon", "Trainer"), ("Vengeful Punch", "OBF", "197", "Uncommon", "Trainer")
            ],
            "Rare": [
                ("Scovillain", "OBF", "025", "Rare", "Pokémon"), ("Entei", "OBF", "030", "Rare", "Pokémon"),
                ("Palafin", "OBF", "062", "Rare", "Pokémon"), ("Thundurus", "OBF", "070", "Rare", "Pokémon"),
                ("Toxtricity", "OBF", "072", "Rare", "Pokémon"), ("Togekiss", "OBF", "085", "Rare", "Pokémon"),
                ("Claydol", "OBF", "095", "Rare", "Pokémon"), ("Darkrai", "OBF", "136", "Rare", "Pokémon"),
                ("Scizor", "OBF", "141", "Rare", "Pokémon"), ("Geeta", "OBF", "188", "Rare", "Trainer")
            ],
            "Double Rare": [
                ("Decidueye ex", "OBF", "015", "Double Rare", "Pokémon"), ("Toedscruel ex", "OBF", "022", "Double Rare", "Pokémon"),
                ("Victini ex", "OBF", "033", "Double Rare", "Pokémon"), ("Eiscue ex", "OBF", "042", "Double Rare", "Pokémon"),
                ("Tyranitar ex", "OBF", "066", "Double Rare", "Pokémon"), ("Pawmot ex", "OBF", "073", "Double Rare", "Pokémon"),
                ("Miraidon ex", "OBF", "079", "Double Rare", "Pokémon"), ("Clefable ex", "OBF", "082", "Double Rare", "Pokémon"),
                ("Vespiquen ex", "OBF", "096", "Double Rare", "Pokémon"), ("Houndstone ex", "OBF", "102", "Double Rare", "Pokémon"),
                ("Klawf ex", "OBF", "120", "Double Rare", "Pokémon"), ("Glimmora ex", "OBF", "123", "Double Rare", "Pokémon"),
                ("Koraidon ex", "OBF", "124", "Double Rare", "Pokémon"), ("Charizard ex", "OBF", "125", "Double Rare", "Pokémon"),
                ("Houndoom ex", "OBF", "134", "Double Rare", "Pokémon"), ("Absol ex", "OBF", "135", "Double Rare", "Pokémon"),
                ("Melmetal ex", "OBF", "153", "Double Rare", "Pokémon"), ("Revavroom ex", "OBF", "156", "Double Rare", "Pokémon"),
                ("Dragonite ex", "OBF", "159", "Double Rare", "Pokémon"), ("Pidgeot ex", "OBF", "164", "Double Rare", "Pokémon"),
                ("Greedent ex", "OBF", "179", "Double Rare", "Pokémon")
            ],
            "Illustration Rare": [
                ("Gloom", "OBF", "198", "Illustration Rare", "Pokémon"), ("Ninetales", "OBF", "199", "Illustration Rare", "Pokémon"),
                ("Palafin", "OBF", "200", "Illustration Rare", "Pokémon"), ("Bellibolt", "OBF", "201", "Illustration Rare", "Pokémon"),
                ("Cleffa", "OBF", "202", "Illustration Rare", "Pokémon"), ("Larvitar", "OBF", "203", "Illustration Rare", "Pokémon"),
                ("Houndour", "OBF", "204", "Illustration Rare", "Pokémon"), ("Scizor", "OBF", "205", "Illustration Rare", "Pokémon"),
                ("Varoom", "OBF", "206", "Illustration Rare", "Pokémon"), ("Pidgey", "OBF", "207", "Illustration Rare", "Pokémon"),
                ("Pidgeotto", "OBF", "208", "Illustration Rare", "Pokémon"), ("Lechonk", "OBF", "209", "Illustration Rare", "Pokémon")
            ],
            "Ultra Rare": [
                ("Eiscue ex", "OBF", "210", "Ultra Rare", "Pokémon"), ("Tyranitar ex", "OBF", "211", "Ultra Rare", "Pokémon"),
                ("Vespiquen ex", "OBF", "212", "Ultra Rare", "Pokémon"), ("Glimmora ex", "OBF", "213", "Ultra Rare", "Pokémon"),
                ("Absol ex", "OBF", "214", "Ultra Rare", "Pokémon"), ("Charizard ex", "OBF", "215", "Ultra Rare", "Pokémon"),
                ("Revavroom ex", "OBF", "216", "Ultra Rare", "Pokémon"), ("Pidgeot ex", "OBF", "217", "Ultra Rare", "Pokémon"),
                ("Geeta", "OBF", "218", "Ultra Rare", "Trainer"), ("Ortega", "OBF", "219", "Ultra Rare", "Trainer"),
                ("Poppy", "OBF", "220", "Ultra Rare", "Trainer"), ("Ryme", "OBF", "221", "Ultra Rare", "Trainer")
            ],
            "Special Illustration Rare": [
                ("Eiscue ex", "OBF", "222", "Special Illustration Rare", "Pokémon"), ("Charizard ex", "OBF", "223", "Special Illustration Rare", "Pokémon"),
                ("Revavroom ex", "OBF", "224", "Special Illustration Rare", "Pokémon"), ("Pidgeot ex", "OBF", "225", "Special Illustration Rare", "Pokémon"),
                ("Geeta", "OBF", "226", "Special Illustration Rare", "Trainer"), ("Poppy", "OBF", "227", "Special Illustration Rare", "Trainer")
            ],
            "Hyper Rare": [
                ("Charizard ex", "OBF", "228", "Hyper Rare", "Pokémon"), ("Artazon", "OBF", "229", "Hyper Rare", "Trainer"),
                ("Basic Fire Energy", "OBF", "230", "Hyper Rare", "Energy")
            ]
        }
    }
}