SV4 = {
    "Paradox Rift": {
        "pull_rates": {
            "P_DR": 1/6, "P_IR": 1/13, "P_UR": 1/15, "P_SIR": 1/47, "P_HR": 1/82
        },
        "card_database": {
            "Common": [
                ("Surskit", "PAR", "001", "Common", "Pokémon"), ("Pansage", "PAR", "004", "Common", "Pokémon"),
                ("Dwebble", "PAR", "006", "Common", "Pokémon"), ("Crustle", "PAR", "007", "Common", "Pokémon"),
                ("Bounsweet", "PAR", "008", "Common", "Pokémon"), ("Blipbug", "PAR", "010", "Common", "Pokémon"),
                ("Dottler", "PAR", "011", "Common", "Pokémon"), ("Nymble", "PAR", "013", "Common", "Pokémon"),
                ("Nymble", "PAR", "014", "Common", "Pokémon"), ("Toedscool", "PAR", "015", "Common", "Pokémon"),
                ("Toedscool", "PAR", "016", "Common", "Pokémon"), ("Magby", "PAR", "019", "Common", "Pokémon"),
                ("Pansear", "PAR", "020", "Common", "Pokémon"), ("Fuecoco", "PAR", "023", "Common", "Pokémon"),
                ("Charcadet", "PAR", "025", "Common", "Pokémon"), ("Charcadet", "PAR", "026", "Common", "Pokémon"),
                ("Horsea", "PAR", "030", "Common", "Pokémon"), ("Seadra", "PAR", "031", "Common", "Pokémon"),
                ("Remoraid", "PAR", "033", "Common", "Pokémon"), ("Octillery", "PAR", "034", "Common", "Pokémon"),
                ("Feebas", "PAR", "035", "Common", "Pokémon"), ("Snorunt", "PAR", "037", "Common", "Pokémon"),
                ("Mantyke", "PAR", "039", "Common", "Pokémon"), ("Panpour", "PAR", "041", "Common", "Pokémon"),
                ("Vanillite", "PAR", "043", "Common", "Pokémon"), ("Vanillish", "PAR", "044", "Common", "Pokémon"),
                ("Wimpod", "PAR", "047", "Common", "Pokémon"), ("Wimpod", "PAR", "048", "Common", "Pokémon"),
                ("Wiglett", "PAR", "051", "Common", "Pokémon"), ("Wiglett", "PAR", "052", "Common", "Pokémon"),
                ("Elekid", "PAR", "059", "Common", "Pokémon"), ("Plusle", "PAR", "060", "Common", "Pokémon"),
                ("Minun", "PAR", "061", "Common", "Pokémon"), ("Blitzle", "PAR", "062", "Common", "Pokémon"),
                ("Joltik", "PAR", "064", "Common", "Pokémon"), ("Galvantula", "PAR", "065", "Common", "Pokémon"),
                ("Oricorio", "PAR", "067", "Common", "Pokémon"), ("Toxel", "PAR", "069", "Common", "Pokémon"),
                ("Natu", "PAR", "071", "Common", "Pokémon"), ("Yamask", "PAR", "075", "Common", "Pokémon"),
                ("Pumpkaboo", "PAR", "077", "Common", "Pokémon"), ("Flittle", "PAR", "079", "Common", "Pokémon"),
                ("Flittle", "PAR", "080", "Common", "Pokémon"), ("Tinkatink", "PAR", "082", "Common", "Pokémon"),
                ("Tinkatink", "PAR", "083", "Common", "Pokémon"), ("Tinkatuff", "PAR", "084", "Common", "Pokémon"),
                ("Gimmighoul", "PAR", "087", "Common", "Pokémon"), ("Gimmighoul", "PAR", "088", "Common", "Pokémon"),
                ("Onix", "PAR", "090", "Common", "Pokémon"), ("Gligar", "PAR", "091", "Common", "Pokémon"),
                ("Gible", "PAR", "094", "Common", "Pokémon"), ("Gabite", "PAR", "095", "Common", "Pokémon"),
                ("Mienfoo", "PAR", "096", "Common", "Pokémon"), ("Nacli", "PAR", "101", "Common", "Pokémon"),
                ("Nacli", "PAR", "102", "Common", "Pokémon"), ("Naclstack", "PAR", "103", "Common", "Pokémon"),
                ("Flamigo", "PAR", "106", "Common", "Pokémon"), ("Zubat", "PAR", "110", "Common", "Pokémon"),
                ("Golbat", "PAR", "111", "Common", "Pokémon"), ("Purrloin", "PAR", "114", "Common", "Pokémon"),
                ("Liepard", "PAR", "115", "Common", "Pokémon"), ("Trubbish", "PAR", "116", "Common", "Pokémon"),
                ("Nickit", "PAR", "119", "Common", "Pokémon"), ("Jirachi", "PAR", "126", "Common", "Pokémon"),
                ("Ferroseed", "PAR", "127", "Common", "Pokémon"), ("Honedge", "PAR", "130", "Common", "Pokémon"),
                ("Honedge", "PAR", "131", "Common", "Pokémon"), ("Doublade", "PAR", "132", "Common", "Pokémon"),
                ("Doublade", "PAR", "133", "Common", "Pokémon"), ("Porygon", "PAR", "142", "Common", "Pokémon"),
                ("Porygon2", "PAR", "143", "Common", "Pokémon"), ("Aipom", "PAR", "145", "Common", "Pokémon"),
                ("Miltank", "PAR", "147", "Common", "Pokémon"), ("Whismur", "PAR", "148", "Common", "Pokémon"),
                ("Loudred", "PAR", "149", "Common", "Pokémon"), ("Spinda", "PAR", "151", "Common", "Pokémon"),
                ("Swablu", "PAR", "152", "Common", "Pokémon"), ("Tandemaus", "PAR", "153", "Common", "Pokémon"),
                ("Tandemaus", "PAR", "154", "Common", "Pokémon"), ("Larry", "PAR", "165", "Common", "Trainer"),
                ("Parasol Lady", "PAR", "169", "Common", "Trainer")
            ],
            "Uncommon": [
                ("Masquerain", "PAR", "002", "Uncommon", "Pokémon"), ("Simisage", "PAR", "005", "Uncommon", "Pokémon"),
                ("Steenee", "PAR", "009", "Uncommon", "Pokémon"), ("Orbeetle", "PAR", "012", "Uncommon", "Pokémon"),
                ("Toedscruel", "PAR", "017", "Uncommon", "Pokémon"), ("Simisear", "PAR", "021", "Uncommon", "Pokémon"),
                ("Crocalor", "PAR", "024", "Uncommon", "Pokémon"), ("Simipour", "PAR", "042", "Uncommon", "Pokémon"),
                ("Vanilluxe", "PAR", "045", "Uncommon", "Pokémon"), ("Wugtrio", "PAR", "053", "Uncommon", "Pokémon"),
                ("Veluza", "PAR", "054", "Uncommon", "Pokémon"), ("Dondozo", "PAR", "055", "Uncommon", "Pokémon"),
                ("Iron Bundle", "PAR", "056", "Uncommon", "Pokémon"), ("Zebstrika", "PAR", "063", "Uncommon", "Pokémon"),
                ("Gourgeist", "PAR", "078", "Uncommon", "Pokémon"), ("Tinkaton", "PAR", "085", "Uncommon", "Pokémon"),
                ("Scream Tail", "PAR", "086", "Uncommon", "Pokémon"), ("Gliscor", "PAR", "092", "Uncommon", "Pokémon"),
                ("Mienshao", "PAR", "097", "Uncommon", "Pokémon"), ("Minior", "PAR", "099", "Uncommon", "Pokémon"),
                ("Klawf", "PAR", "105", "Uncommon", "Pokémon"), ("Slither Wing", "PAR", "107", "Uncommon", "Pokémon"),
                ("Crobat", "PAR", "112", "Uncommon", "Pokémon"), ("Absol", "PAR", "113", "Uncommon", "Pokémon"),
                ("Garbodor", "PAR", "117", "Uncommon", "Pokémon"), ("Ferrothorn", "PAR", "128", "Uncommon", "Pokémon"),
                ("Durant", "PAR", "129", "Uncommon", "Pokémon"), ("Orthworm", "PAR", "138", "Uncommon", "Pokémon"),
                ("Tatsugiri", "PAR", "141", "Uncommon", "Pokémon"), ("Ambipom", "PAR", "146", "Uncommon", "Pokémon"),
                ("Exploud", "PAR", "150", "Uncommon", "Pokémon"), ("Cyclizar", "PAR", "157", "Uncommon", "Pokémon"),
                ("Ancient Booster Energy Capsule", "PAR", "159", "Uncommon", "Trainer"), ("Counter Catcher", "PAR", "160", "Uncommon", "Trainer"),
                ("Cursed Duster", "PAR", "161", "Uncommon", "Trainer"), ("Defiance Vest", "PAR", "162", "Uncommon", "Trainer"),
                ("Earthen Vessel", "PAR", "163", "Uncommon", "Trainer"), ("Future Booster Energy Capsule", "PAR", "164", "Uncommon", "Trainer"),
                ("Luxurious Cape", "PAR", "166", "Uncommon", "Trainer"), ("Mela", "PAR", "167", "Uncommon", "Trainer"),
                ("Norman", "PAR", "168", "Uncommon", "Trainer"), ("Professor Sada’s Vitality", "PAR", "170", "Uncommon", "Trainer"),
                ("Professor Turo’s Scenario", "PAR", "171", "Uncommon", "Trainer"), ("Rika", "PAR", "172", "Uncommon", "Trainer"),
                ("Roark", "PAR", "173", "Uncommon", "Trainer"), ("Shauntal", "PAR", "174", "Uncommon", "Trainer"),
                ("Snorlax Doll", "PAR", "175", "Uncommon", "Trainer"), ("Technical Machine: Blindside", "PAR", "176", "Uncommon", "Trainer"),
                ("Technical Machine: Devolution", "PAR", "177", "Uncommon", "Trainer"), ("Technical Machine: Evolution", "PAR", "178", "Uncommon", "Trainer"),
                ("Technical Machine: Turbo Energize", "PAR", "179", "Uncommon", "Trainer"), ("Techno Radar", "PAR", "180", "Uncommon", "Trainer"),
                ("Tulip", "PAR", "181", "Uncommon", "Trainer"), ("Medical Energy", "PAR", "182", "Uncommon", "Energy")
            ],
            "Rare": [
                ("Wo-Chien", "PAR", "018", "Rare", "Pokémon"), ("Volcanion", "PAR", "022", "Rare", "Pokémon"),
                ("Iron Moth", "PAR", "028", "Rare", "Pokémon"), ("Chi-Yu", "PAR", "029", "Rare", "Pokémon"),
                ("Kingdra", "PAR", "032", "Rare", "Pokémon"), ("Milotic", "PAR", "036", "Rare", "Pokémon"),
                ("Palkia", "PAR", "040", "Rare", "Pokémon"), ("Golisopod", "PAR", "049", "Rare", "Pokémon"),
                ("Chien-Pao", "PAR", "057", "Rare", "Pokémon"), ("Zekrom", "PAR", "066", "Rare", "Pokémon"),
                ("Xatu", "PAR", "072", "Rare", "Pokémon"), ("Latios", "PAR", "073", "Rare", "Pokémon"),
                ("Deoxys", "PAR", "074", "Rare", "Pokémon"), ("Espathra", "PAR", "081", "Rare", "Pokémon"),
                ("Groudon", "PAR", "093", "Rare", "Pokémon"), ("Garganacl", "PAR", "104", "Rare", "Pokémon"),
                ("Ting-Lu", "PAR", "109", "Rare", "Pokémon"), ("Yveltal", "PAR", "118", "Rare", "Pokémon"),
                ("Thievul", "PAR", "120", "Rare", "Pokémon"), ("Morpeko", "PAR", "121", "Rare", "Pokémon"),
                ("Lokix", "PAR", "122", "Rare", "Pokémon"), ("Brute Bonnet", "PAR", "123", "Rare", "Pokémon"),
                ("Steelix", "PAR", "125", "Rare", "Pokémon"), ("Aegislash", "PAR", "134", "Rare", "Pokémon"),
                ("Zacian", "PAR", "136", "Rare", "Pokémon"), ("Porygon-Z", "PAR", "144", "Rare", "Pokémon"),
                ("Iron Jugulis", "PAR", "158", "Rare", "Pokémon")
            ],
            "Double Rare": [
                ("Froslass ex", "PAR", "003", "Double Rare", "Pokémon"), ("Armarouge ex", "PAR", "027", "Double Rare", "Pokémon"),
                ("Garchomp ex", "PAR", "038", "Double Rare", "Pokémon"), ("Tsareena ex", "PAR", "046", "Double Rare", "Pokémon"),
                ("Golisopod ex", "PAR", "050", "Double Rare", "Pokémon"), ("Mewtwo ex", "PAR", "058", "Double Rare", "Pokémon"),
                ("Tapu Koko ex", "PAR", "068", "Double Rare", "Pokémon"), ("Iron Hands ex", "PAR", "070", "Double Rare", "Pokémon"),
                ("Cofagrigus ex", "PAR", "076", "Double Rare", "Pokémon"), ("Iron Valiant ex", "PAR", "089", "Double Rare", "Pokémon"),
                ("Hoopa ex", "PAR", "098", "Double Rare", "Pokémon"), ("Toxtricity ex", "PAR", "100", "Double Rare", "Pokémon"),
                ("Sandy Shocks ex", "PAR", "108", "Double Rare", "Pokémon"), ("Roaring Moon ex", "PAR", "124", "Double Rare", "Pokémon"),
                ("Aegislash ex", "PAR", "135", "Double Rare", "Pokémon"), ("Skeledirge ex", "PAR", "137", "Double Rare", "Pokémon"),
                ("Gholdengo ex", "PAR", "139", "Double Rare", "Pokémon"), ("Altaria ex", "PAR", "140", "Double Rare", "Pokémon"),
                ("Maushold ex", "PAR", "155", "Double Rare", "Pokémon"), ("Bombirdier ex", "PAR", "156", "Double Rare", "Pokémon")
            ],
            "Illustration Rare": [
                ("Crustle", "PAR", "183", "Illustration Rare", "Pokémon"), ("Dottler", "PAR", "184", "Illustration Rare", "Pokémon"),
                ("Toedscruel", "PAR", "185", "Illustration Rare", "Pokémon"), ("Magby", "PAR", "186", "Illustration Rare", "Pokémon"),
                ("Iron Moth", "PAR", "187", "Illustration Rare", "Pokémon"), ("Snorunt", "PAR", "188", "Illustration Rare", "Pokémon"),
                ("Mantyke", "PAR", "189", "Illustration Rare", "Pokémon"), ("Vanillish", "PAR", "190", "Illustration Rare", "Pokémon"),
                ("Wimpod", "PAR", "191", "Illustration Rare", "Pokémon"), ("Veluza", "PAR", "192", "Illustration Rare", "Pokémon"),
                ("Plusle", "PAR", "193", "Illustration Rare", "Pokémon"), ("Minun", "PAR", "194", "Illustration Rare", "Pokémon"),
                ("Blitzle", "PAR", "195", "Illustration Rare", "Pokémon"), ("Joltik", "PAR", "196", "Illustration Rare", "Pokémon"),
                ("Espathra", "PAR", "197", "Illustration Rare", "Pokémon"), ("Gimmighoul", "PAR", "198", "Illustration Rare", "Pokémon"),
                ("Groudon", "PAR", "199", "Illustration Rare", "Pokémon"), ("Mienshao", "PAR", "200", "Illustration Rare", "Pokémon"),
                ("Minior", "PAR", "201", "Illustration Rare", "Pokémon"), ("Garganacl", "PAR", "202", "Illustration Rare", "Pokémon"),
                ("Slither Wing", "PAR", "203", "Illustration Rare", "Pokémon"), ("Garbodor", "PAR", "204", "Illustration Rare", "Pokémon"),
                ("Yveltal", "PAR", "205", "Illustration Rare", "Pokémon"), ("Morpeko", "PAR", "206", "Illustration Rare", "Pokémon"),
                ("Brute Bonnet", "PAR", "207", "Illustration Rare", "Pokémon"), ("Steelix", "PAR", "208", "Illustration Rare", "Pokémon"),
                ("Ferrothorn", "PAR", "209", "Illustration Rare", "Pokémon"), ("Aegislash", "PAR", "210", "Illustration Rare", "Pokémon"),
                ("Aipom", "PAR", "211", "Illustration Rare", "Pokémon"), ("Loudred", "PAR", "212", "Illustration Rare", "Pokémon"),
                ("Swablu", "PAR", "213", "Illustration Rare", "Pokémon"), ("Porygon-Z", "PAR", "214", "Illustration Rare", "Pokémon"),
                ("Cyclizar", "PAR", "215", "Illustration Rare", "Pokémon"), ("Iron Jugulis", "PAR", "216", "Illustration Rare", "Pokémon")
            ],
            "Ultra Rare": [
                ("Froslass ex", "PAR", "217", "Ultra Rare", "Pokémon"), ("Armarouge ex", "PAR", "218", "Ultra Rare", "Pokémon"),
                ("Garchomp ex", "PAR", "219", "Ultra Rare", "Pokémon"), ("Tsareena ex", "PAR", "220", "Ultra Rare", "Pokémon"),
                ("Golisopod ex", "PAR", "221", "Ultra Rare", "Pokémon"), ("Tapu Koko ex", "PAR", "222", "Ultra Rare", "Pokémon"),
                ("Iron Hands ex", "PAR", "223", "Ultra Rare", "Pokémon"), ("Cofagrigus ex", "PAR", "224", "Ultra Rare", "Pokémon"),
                ("Iron Valiant ex", "PAR", "225", "Ultra Rare", "Pokémon"), ("Hoopa ex", "PAR", "226", "Ultra Rare", "Pokémon"),
                ("Toxtricity ex", "PAR", "227", "Ultra Rare", "Pokémon"), ("Sandy Shocks ex", "PAR", "228", "Ultra Rare", "Pokémon"),
                ("Roaring Moon ex", "PAR", "229", "Ultra Rare", "Pokémon"), ("Aegislash ex", "PAR", "230", "Ultra Rare", "Pokémon"),
                ("Gholdengo ex", "PAR", "231", "Ultra Rare", "Pokémon"), ("Altaria ex", "PAR", "232", "Ultra Rare", "Pokémon"),
                ("Maushold ex", "PAR", "233", "Ultra Rare", "Pokémon"), ("Bombirdier ex", "PAR", "234", "Ultra Rare", "Pokémon"),
                ("Larry", "PAR", "235", "Ultra Rare", "Trainer"), ("Mela", "PAR", "236", "Ultra Rare", "Trainer"),
                ("Norman", "PAR", "237", "Ultra Rare", "Trainer"), ("Parasol Lady", "PAR", "238", "Ultra Rare", "Trainer"),
                ("Professor Sada’s Vitality", "PAR", "239", "Ultra Rare", "Trainer"), ("Professor Turo’s Scenario", "PAR", "240", "Ultra Rare", "Trainer"),
                ("Rika", "PAR", "241", "Ultra Rare", "Trainer"), ("Roark", "PAR", "242", "Ultra Rare", "Trainer"),
                ("Shauntal", "PAR", "243", "Ultra Rare", "Trainer"), ("Tulip", "PAR", "244", "Ultra Rare", "Trainer")
            ],
            "Special Illustration Rare": [
                ("Garchomp ex", "PAR", "245", "Special Illustration Rare", "Pokémon"), ("Golisopod ex", "PAR", "246", "Special Illustration Rare", "Pokémon"),
                ("Tapu Koko ex", "PAR", "247", "Special Illustration Rare", "Pokémon"), ("Iron Hands ex", "PAR", "248", "Special Illustration Rare", "Pokémon"),
                ("Iron Valiant ex", "PAR", "249", "Special Illustration Rare", "Pokémon"), ("Sandy Shocks ex", "PAR", "250", "Special Illustration Rare", "Pokémon"),
                ("Roaring Moon ex", "PAR", "251", "Special Illustration Rare", "Pokémon"), ("Gholdengo ex", "PAR", "252", "Special Illustration Rare", "Pokémon"),
                ("Altaria ex", "PAR", "253", "Special Illustration Rare", "Pokémon"), ("Mela", "PAR", "254", "Special Illustration Rare", "Trainer"),
                ("Parasol Lady", "PAR", "255", "Special Illustration Rare", "Trainer"), ("Professor Sada’s Vitality", "PAR", "256", "Special Illustration Rare", "Trainer"),
                ("Professor Turo’s Scenario", "PAR", "257", "Special Illustration Rare", "Trainer"), ("Rika", "PAR", "258", "Special Illustration Rare", "Trainer"),
                ("Tulip", "PAR", "259", "Special Illustration Rare", "Trainer")
            ],
            "Hyper Rare": [
                ("Garchomp ex", "PAR", "260", "Hyper Rare", "Pokémon"), ("Iron Valiant ex", "PAR", "261", "Hyper Rare", "Pokémon"),
                ("Roaring Moon ex", "PAR", "262", "Hyper Rare", "Pokémon"), ("Beach Court", "PAR", "263", "Hyper Rare", "Trainer"),
                ("Counter Catcher", "PAR", "264", "Hyper Rare", "Trainer"), ("Luxurious Cape", "PAR", "265", "Hyper Rare", "Trainer"),
                ("Reversal Energy", "PAR", "266", "Hyper Rare", "Energy")
            ]
        }
    }
}