SV8 = {
    "Surging Sparks": {
        "pull_rates": {
            "P_DR": 1/6, "P_ASR": 1/20, "P_IR": 1/13, "P_UR": 1/15, "P_SIR": 1/87, "P_HR": 1/188
        },
        "card_database": {
            "Common": [
                ("Exeggcute", "SSP", "001", "Common", "Pokémon"), ("Exeggcute", "SSP", "002", "Common", "Pokémon"),
                ("Scatterbug", "SSP", "005", "Common", "Pokémon"), ("Spewpa", "SSP", "006", "Common", "Pokémon"),
                ("Morelull", "SSP", "008", "Common", "Pokémon"), ("Dhelmise", "SSP", "010", "Common", "Pokémon"),
                ("Capsakid", "SSP", "012", "Common", "Pokémon"), ("Rellor", "SSP", "013", "Common", "Pokémon"),
                ("Vulpix", "SSP", "016", "Common", "Pokémon"), ("Castform Sunny Form", "SSP", "020", "Common", "Pokémon"),
                ("Pansear", "SSP", "022", "Common", "Pokémon"), ("Simisear", "SSP", "023", "Common", "Pokémon"),
                ("Larvesta", "SSP", "024", "Common", "Pokémon"), ("Volcarona", "SSP", "025", "Common", "Pokémon"),
                ("Oricorio", "SSP", "026", "Common", "Pokémon"), ("Sizzlipede", "SSP", "027", "Common", "Pokémon"),
                ("Centiskorch", "SSP", "028", "Common", "Pokémon"), ("Fuecoco", "SSP", "029", "Common", "Pokémon"),
                ("Crocalor", "SSP", "030", "Common", "Pokémon"), ("Charcadet", "SSP", "032", "Common", "Pokémon"),
                ("Charcadet", "SSP", "033", "Common", "Pokémon"), ("Mantine", "SSP", "040", "Common", "Pokémon"),
                ("Feebas", "SSP", "041", "Common", "Pokémon"), ("Spheal", "SSP", "043", "Common", "Pokémon"),
                ("Sealeo", "SSP", "044", "Common", "Pokémon"), ("Shellos", "SSP", "046", "Common", "Pokémon"),
                ("Cryogonal", "SSP", "047", "Common", "Pokémon"), ("Quaxly", "SSP", "050", "Common", "Pokémon"),
                ("Quaxwell", "SSP", "051", "Common", "Pokémon"), ("Cetoddle", "SSP", "053", "Common", "Pokémon"),
                ("Cetitan", "SSP", "054", "Common", "Pokémon"), ("Magnemite", "SSP", "058", "Common", "Pokémon"),
                ("Rotom", "SSP", "061", "Common", "Pokémon"), ("Blitzle", "SSP", "062", "Common", "Pokémon"),
                ("Zebstrika", "SSP", "063", "Common", "Pokémon"), ("Stunfisk", "SSP", "064", "Common", "Pokémon"),
                ("Wattrel", "SSP", "066", "Common", "Pokémon"), ("Togepi", "SSP", "070", "Common", "Pokémon"),
                ("Togetic", "SSP", "071", "Common", "Pokémon"), ("Marill", "SSP", "073", "Common", "Pokémon"),
                ("Smoochum", "SSP", "075", "Common", "Pokémon"), ("Uxie", "SSP", "078", "Common", "Pokémon"),
                ("Mesprit", "SSP", "079", "Common", "Pokémon"), ("Azelf", "SSP", "080", "Common", "Pokémon"),
                ("Sigilyph", "SSP", "081", "Common", "Pokémon"), ("Yamask", "SSP", "082", "Common", "Pokémon"),
                ("Espurr", "SSP", "084", "Common", "Pokémon"), ("Dedenne", "SSP", "087", "Common", "Pokémon"),
                ("Oricorio", "SSP", "089", "Common", "Pokémon"), ("Sandygast", "SSP", "090", "Common", "Pokémon"),
                ("Flittle", "SSP", "094", "Common", "Pokémon"), ("Gimmighoul", "SSP", "097", "Common", "Pokémon"),
                ("Mankey", "SSP", "098", "Common", "Pokémon"), ("Primeape", "SSP", "099", "Common", "Pokémon"),
                ("Phanpy", "SSP", "102", "Common", "Pokémon"), ("Donphan", "SSP", "103", "Common", "Pokémon"),
                ("Trapinch", "SSP", "104", "Common", "Pokémon"), ("Vibrava", "SSP", "105", "Common", "Pokémon"),
                ("Drilbur", "SSP", "108", "Common", "Pokémon"), ("Excadrill", "SSP", "109", "Common", "Pokémon"),
                ("Clobbopus", "SSP", "112", "Common", "Pokémon"), ("Grapploct", "SSP", "113", "Common", "Pokémon"),
                ("Glimmet", "SSP", "114", "Common", "Pokémon"), ("Glimmora", "SSP", "115", "Common", "Pokémon"),
                ("Deino", "SSP", "117", "Common", "Pokémon"), ("Zweilous", "SSP", "118", "Common", "Pokémon"),
                ("Shroodle", "SSP", "120", "Common", "Pokémon"), ("Alolan Diglett", "SSP", "122", "Common", "Pokémon"),
                ("Skarmory", "SSP", "124", "Common", "Pokémon"), ("Bronzor", "SSP", "126", "Common", "Pokémon"),
                ("Bronzong", "SSP", "127", "Common", "Pokémon"), ("Klefki", "SSP", "128", "Common", "Pokémon"),
                ("Duraludon", "SSP", "129", "Common", "Pokémon"), ("Applin", "SSP", "138", "Common", "Pokémon"),
                ("Eevee", "SSP", "143", "Common", "Pokémon"), ("Snorlax", "SSP", "144", "Common", "Pokémon"),
                ("Slakoth", "SSP", "145", "Common", "Pokémon"), ("Vigoroth", "SSP", "146", "Common", "Pokémon"),
                ("Swablu", "SSP", "148", "Common", "Pokémon"), ("Zangoose", "SSP", "149", "Common", "Pokémon"),
                ("Kecleon", "SSP", "150", "Common", "Pokémon"), ("Bouffalant", "SSP", "151", "Common", "Pokémon"),
                ("Rufflet", "SSP", "152", "Common", "Pokémon"), ("Helioptile", "SSP", "154", "Common", "Pokémon"),
                ("Heliolisk", "SSP", "155", "Common", "Pokémon"), ("Oranguru", "SSP", "156", "Common", "Pokémon"),
                ("Tandemaus", "SSP", "157", "Common", "Pokémon"), ("Drasna", "SSP", "173", "Common", "Trainer")
            ],
            "Uncommon": [
                ("Exeggutor", "SSP", "003", "Uncommon", "Pokémon"), ("Vivillon", "SSP", "007", "Uncommon", "Pokémon"),
                ("Shiinotic", "SSP", "009", "Uncommon", "Pokémon"), ("Wo-Chien", "SSP", "015", "Uncommon", "Pokémon"),
                ("Ninetales", "SSP", "017", "Uncommon", "Pokémon"), ("Paldean Tauros", "SSP", "018", "Uncommon", "Pokémon"),
                ("Ho-Oh", "SSP", "019", "Uncommon", "Pokémon"), ("Victini", "SSP", "021", "Uncommon", "Pokémon"),
                ("Armarouge", "SSP", "034", "Uncommon", "Pokémon"), ("Ceruledge", "SSP", "035", "Uncommon", "Pokémon"),
                ("Paldean Tauros", "SSP", "039", "Uncommon", "Pokémon"), ("Walrein", "SSP", "045", "Uncommon", "Pokémon"),
                ("Bruxish", "SSP", "049", "Uncommon", "Pokémon"), ("Quaquaval", "SSP", "052", "Uncommon", "Pokémon"),
                ("Iron Bundle", "SSP", "055", "Uncommon", "Pokémon"), ("Magneton", "SSP", "059", "Uncommon", "Pokémon"),
                ("Magnezone", "SSP", "060", "Uncommon", "Pokémon"), ("Kilowattrel", "SSP", "067", "Uncommon", "Pokémon"),
                ("Miraidon", "SSP", "069", "Uncommon", "Pokémon"), ("Azumarill", "SSP", "074", "Uncommon", "Pokémon"),
                ("Latios", "SSP", "077", "Uncommon", "Pokémon"), ("Meowstic", "SSP", "085", "Uncommon", "Pokémon"),
                ("Xerneas", "SSP", "088", "Uncommon", "Pokémon"), ("Indeedee", "SSP", "093", "Uncommon", "Pokémon"),
                ("Espathra", "SSP", "095", "Uncommon", "Pokémon"), ("Flutter Mane", "SSP", "096", "Uncommon", "Pokémon"),
                ("Annihilape", "SSP", "100", "Uncommon", "Pokémon"), ("Paldean Tauros", "SSP", "101", "Uncommon", "Pokémon"),
                ("Passimian", "SSP", "111", "Uncommon", "Pokémon"), ("Koraidon", "SSP", "116", "Uncommon", "Pokémon"),
                ("Grafaiai", "SSP", "121", "Uncommon", "Pokémon"), ("Alolan Dugtrio", "SSP", "123", "Uncommon", "Pokémon"),
                ("Registeel", "SSP", "125", "Uncommon", "Pokémon"), ("Gholdengo", "SSP", "131", "Uncommon", "Pokémon"),
                ("Altaria", "SSP", "134", "Uncommon", "Pokémon"), ("Turtonator", "SSP", "137", "Uncommon", "Pokémon"),
                ("Flapple", "SSP", "139", "Uncommon", "Pokémon"), ("Appletun", "SSP", "140", "Uncommon", "Pokémon"),
                ("Braviary", "SSP", "153", "Uncommon", "Pokémon"), ("Maushold", "SSP", "158", "Uncommon", "Pokémon"),
                ("Babiri Berry", "SSP", "163", "Uncommon", "Trainer"), ("Call Bell", "SSP", "165", "Uncommon", "Trainer"),
                ("Chill Teaser Toy", "SSP", "166", "Uncommon", "Trainer"), ("Clemont’s Quick Wit", "SSP", "167", "Uncommon", "Trainer"),
                ("Colbur Berry", "SSP", "168", "Uncommon", "Trainer"), ("Counter Gain", "SSP", "169", "Uncommon", "Trainer"),
                ("Cyrano", "SSP", "170", "Uncommon", "Trainer"), ("Deduction Kit", "SSP", "171", "Uncommon", "Trainer"),
                ("Dragon Elixir", "SSP", "172", "Uncommon", "Trainer"), ("Drayton", "SSP", "174", "Uncommon", "Trainer"),
                ("Dusk Ball", "SSP", "175", "Uncommon", "Trainer"), ("Gravity Mountain", "SSP", "177", "Uncommon", "Trainer"),
                ("Jasmine’s Gaze", "SSP", "178", "Uncommon", "Trainer"), ("Lisia’s Appeal", "SSP", "179", "Uncommon", "Trainer"),
                ("Lively Stadium", "SSP", "180", "Uncommon", "Trainer"), ("Meddling Memo", "SSP", "181", "Uncommon", "Trainer"),
                ("Passho Berry", "SSP", "184", "Uncommon", "Trainer"), ("Surfer", "SSP", "187", "Uncommon", "Trainer"),
                ("Technical Machine: Fluorite", "SSP", "188", "Uncommon", "Trainer"), ("Tera Orb", "SSP", "189", "Uncommon", "Trainer"),
                ("Tyme", "SSP", "190", "Uncommon", "Trainer")
            ],
            "Rare": [
                ("Zarude", "SSP", "011", "Rare", "Pokémon"), ("Rabsca", "SSP", "014", "Rare", "Pokémon"),
                ("Skeledirge", "SSP", "031", "Rare", "Pokémon"), ("Gouging Fire", "SSP", "038", "Rare", "Pokémon"),
                ("Chien-Pao", "SSP", "056", "Rare", "Pokémon"), ("Tapu Koko", "SSP", "065", "Rare", "Pokémon"),
                ("Togekiss", "SSP", "072", "Rare", "Pokémon"), ("Cofagrigus", "SSP", "083", "Rare", "Pokémon"),
                ("Tapu Lele", "SSP", "092", "Rare", "Pokémon"), ("Gastrodon", "SSP", "107", "Rare", "Pokémon"),
                ("Landorus", "SSP", "110", "Rare", "Pokémon"), ("Iron Crown", "SSP", "132", "Rare", "Pokémon"),
                ("Dialga", "SSP", "135", "Rare", "Pokémon"), ("Palkia", "SSP", "136", "Rare", "Pokémon"),
                ("Eternatus", "SSP", "141", "Rare", "Pokémon"), ("Terapagos", "SSP", "161", "Rare", "Pokémon")
            ],
            "Double Rare": [
                ("Durant ex", "SSP", "004", "Double Rare", "Pokémon"), ("Ceruledge ex", "SSP", "036", "Double Rare", "Pokémon"),
                ("Scovillain ex", "SSP", "037", "Double Rare", "Pokémon"), ("Milotic ex", "SSP", "042", "Double Rare", "Pokémon"),
                ("Black Kyurem ex", "SSP", "048", "Double Rare", "Pokémon"), ("Pikachu ex", "SSP", "057", "Double Rare", "Pokémon"),
                ("Kilowattrel ex", "SSP", "068", "Double Rare", "Pokémon"), ("Latias ex", "SSP", "076", "Double Rare", "Pokémon"),
                ("Sylveon ex", "SSP", "086", "Double Rare", "Pokémon"), ("Palossand ex", "SSP", "091", "Double Rare", "Pokémon"),
                ("Medicham ex", "SSP", "080", "Double Rare", "Pokémon"), ("Lucario ex", "SSP", "082", "Double Rare", "Pokémon"),
                ("Flygon ex", "SSP", "106", "Double Rare", "Pokémon"), ("Hydreigon ex", "SSP", "119", "Double Rare", "Pokémon"),
                ("Archaludon ex", "SSP", "130", "Double Rare", "Pokémon"), ("Alolan Exeggutor ex", "SSP", "133", "Double Rare", "Pokémon"),
                ("Tatsugiri ex", "SSP", "142", "Double Rare", "Pokémon"), ("Slaking ex", "SSP", "147", "Double Rare", "Pokémon"),
                ("Cyclizar ex", "SSP", "159", "Double Rare", "Pokémon"), ("Flamigo ex", "SSP", "160", "Double Rare", "Pokémon")
            ],
            "ACE SPEC": [
                ("Amulet of Hope", "SSP", "162", "ACE SPEC", "Trainer"), ("Brilliant Blender", "SSP", "164", "ACE SPEC", "Trainer"),
                ("Energy Search Pro", "SSP", "176", "ACE SPEC", "Trainer"), ("Megaton Blower", "SSP", "182", "ACE SPEC", "Trainer"),
                ("Miracle Headset", "SSP", "183", "ACE SPEC", "Trainer"), ("Precious Trolley", "SSP", "185", "ACE SPEC", "Trainer"),
                ("Scramble Switch", "SSP", "186", "ACE SPEC", "Trainer"), ("Enriching Energy", "SSP", "191", "ACE SPEC", "Energy")
            ],
            "Illustration Rare": [
                ("Exeggcute", "SSP", "192", "Illustration Rare", "Pokémon"), ("Vivillon", "SSP", "193", "Illustration Rare", "Pokémon"),
                ("Shiinotic", "SSP", "194", "Illustration Rare", "Pokémon"), ("Castform Sunny Form", "SSP", "195", "Illustration Rare", "Pokémon"),
                ("Larvesta", "SSP", "196", "Illustration Rare", "Pokémon"), ("Ceruledge", "SSP", "197", "Illustration Rare", "Pokémon"),
                ("Feebas", "SSP", "198", "Illustration Rare", "Pokémon"), ("Spheal", "SSP", "199", "Illustration Rare", "Pokémon"),
                ("Bruxish", "SSP", "200", "Illustration Rare", "Pokémon"), ("Cetitan", "SSP", "201", "Illustration Rare", "Pokémon"),
                ("Stunfisk", "SSP", "202", "Illustration Rare", "Pokémon"), ("Latios", "SSP", "203", "Illustration Rare", "Pokémon"),
                ("Mesprit", "SSP", "204", "Illustration Rare", "Pokémon"), ("Phanpy", "SSP", "205", "Illustration Rare", "Pokémon"),
                ("Vibrava", "SSP", "206", "Illustration Rare", "Pokémon"), ("Clobbopus", "SSP", "207", "Illustration Rare", "Pokémon"),
                ("Alolan Dugtrio", "SSP", "208", "Illustration Rare", "Pokémon"), ("Skarmory", "SSP", "209", "Illustration Rare", "Pokémon"),
                ("Flapple", "SSP", "210", "Illustration Rare", "Pokémon"), ("Appletun", "SSP", "211", "Illustration Rare", "Pokémon"),
                ("Slakoth", "SSP", "212", "Illustration Rare", "Pokémon"), ("Kecleon", "SSP", "213", "Illustration Rare", "Pokémon"),
                ("Braviary", "SSP", "214", "Illustration Rare", "Pokémon")
            ],
            "Ultra Rare": [
                ("Durant ex", "SSP", "215", "Ultra Rare", "Pokémon"), ("Scovillain ex", "SSP", "216", "Ultra Rare", "Pokémon"),
                ("Milotic ex", "SSP", "217", "Ultra Rare", "Pokémon"), ("Black Kyurem ex", "SSP", "218", "Ultra Rare", "Pokémon"),
                ("Pikachu ex", "SSP", "219", "Ultra Rare", "Pokémon"), ("Latias ex", "SSP", "220", "Ultra Rare", "Pokémon"),
                ("Palossand ex", "SSP", "221", "Ultra Rare", "Pokémon"), ("Flygon ex", "SSP", "222", "Ultra Rare", "Pokémon"),
                ("Hydreigon ex", "SSP", "223", "Ultra Rare", "Pokémon"), ("Archaludon ex", "SSP", "224", "Ultra Rare", "Pokémon"),
                ("Alolan Exeggutor ex", "SSP", "225", "Ultra Rare", "Pokémon"), ("Tatsugiri ex", "SSP", "226", "Ultra Rare", "Pokémon"),
                ("Slaking ex", "SSP", "227", "Ultra Rare", "Pokémon"), ("Cyclizar ex", "SSP", "228", "Ultra Rare", "Pokémon"),
                ("Clemont’s Quick Wit", "SSP", "229", "Ultra Rare", "Trainer"), ("Cyrano", "SSP", "230", "Ultra Rare", "Trainer"),
                ("Drasna", "SSP", "231", "Ultra Rare", "Trainer"), ("Drayton", "SSP", "232", "Ultra Rare", "Trainer"),
                ("Jasmine’s Gaze", "SSP", "233", "Ultra Rare", "Trainer"), ("Lisia’s Appeal", "SSP", "234", "Ultra Rare", "Trainer"),
                ("Surfer", "SSP", "235", "Ultra Rare", "Trainer")
            ],
            "Special Illustration Rare": [
                ("Durant ex", "SSP", "236", "Special Illustration Rare", "Pokémon"), ("Milotic ex", "SSP", "237", "Special Illustration Rare", "Pokémon"),
                ("Pikachu ex", "SSP", "238", "Special Illustration Rare", "Pokémon"), ("Latias ex", "SSP", "239", "Special Illustration Rare", "Pokémon"),
                ("Hydreigon ex", "SSP", "240", "Special Illustration Rare", "Pokémon"), ("Archaludon ex", "SSP", "241", "Special Illustration Rare", "Pokémon"),
                ("Alolan Exeggutor ex", "SSP", "242", "Special Illustration Rare", "Pokémon"), ("Clemont’s Quick Wit", "SSP", "243", "Special Illustration Rare", "Trainer"),
                ("Drayton", "SSP", "244", "Special Illustration Rare", "Trainer"), ("Jasmine’s Gaze", "SSP", "245", "Special Illustration Rare", "Trainer"),
                ("Lisia’s Appeal", "SSP", "246", "Special Illustration Rare", "Trainer")
            ],
            "Hyper Rare": [
                ("Pikachu ex", "SSP", "247", "Hyper Rare", "Pokémon"), ("Alolan Exeggutor ex", "SSP", "248", "Hyper Rare", "Pokémon"),
                ("Counter Gain", "SSP", "249", "Hyper Rare", "Trainer"), ("Gravity Mountain", "SSP", "250", "Hyper Rare", "Trainer"),
                ("Night Stretcher", "SSP", "251", "Hyper Rare", "Trainer"), ("Jet Energy", "SSP", "252", "Hyper Rare", "Energy")
            ]
        }
    }
}